exam/src/main/java/in/testpress/exam/ui/TestFragment.java
exam/src/main/res/values/strings.xml

When writing an exam and if internet gets disconnected, a dialog is
shown with Retry button. To make it cancelable 'Not Now' button is
added. So that user can pause the exam and return to main page.
Fixes #21

Allow cancel dialog if no internet during writing exam

---

core/src/main/java/in/testpress/core/TestpressSdk.java

Stored the user id in shared preferences while storing the session at
the first time.
Here after while they initialize, if the passed userId is same as the
shared prefs, don't do network request. Returned session from shared
prefs.
Fixes #25

Handle multiple initialization of sdk intelligently

---

.travis.yml
build.gradle
core/build.gradle
core/src/androidTest/java/in/testpress/util/ImageUtilsTest.java
core/src/main/java/in/testpress/util/ImageUtils.java
core/src/main/java/in/testpress/util/UILImageGetter.java
core/src/main/res/layout/testpress_toolbar.xml
core/src/main/res/values/styles.xml
exam/build.gradle
exam/src/androidTest/java/in/testpress/exam/ui/ReviewActivityTest.java
exam/src/androidTest/java/in/testpress/exam/util/ElapsedTimeIdlingResource.java
exam/src/main/AndroidManifest.xml
exam/src/main/java/in/testpress/exam/TestpressExam.java
exam/src/main/java/in/testpress/exam/ui/ReviewActivity.java
exam/src/main/java/in/testpress/exam/ui/ReviewFragment.java
exam/src/main/java/in/testpress/exam/ui/ReviewQuestionsFragment.java
exam/src/main/java/in/testpress/exam/ui/ReviewStatsFragment.java
exam/src/main/res/values/styles.xml
samples/lint.xml

On resuming app from background state, ImageLoader which has initiated
previously may destroy. So that app may crash while tries to access it,
it is fixed by initiating the ImageLoader if an instance not exist.
And ReviewFragment will crash due to accessing destroyed activity in the
async task, it is fixed now.
Renamed app theme.
Modified travis to use sudo-enabled precise infrastructure and emulator.

Fix crash on resume app from background & rename app theme

---

exam/src/main/java/in/testpress/exam/TestpressExam.java
exam/src/main/java/in/testpress/exam/network/ExamService.java
exam/src/main/java/in/testpress/exam/network/TestpressExamApiClient.java
exam/src/main/java/in/testpress/exam/ui/TestActivity.java
exam/src/main/res/values/strings.xml
exam/src/test/java/in/testpress/exam/TestpressExamTest.java
samples/src/main/java/in/testpress/samples/exam/ExamSampleActivity.java
samples/src/main/res/layout/activity_login.xml
samples/src/main/res/layout/activity_open_exams_as.xml
samples/src/main/res/layout/edit_text_dialog_box.xml
samples/src/main/res/values/styles.xml

An exam can directly start using exam slug.
Result code sent to the onActivityResult() of activity which calls the
start exam API.(To support refresh & deep linking on user app).
* RESULT_OK - If the user started the exam(started the exam & pause or
completed).
* RESULT_CANCELLED - If the user didn't start the exam and navigated
back from the start exam screen. Additionally, an Intent is passed in
the result with a boolean based on the user action as below.
* True - If the user pressed home icon(left navigation arrow) in the
app.
* False - If the user pressed back button on the device.
Provided sample implementation.
Fix #47

Provide API to start exam using the slug

---

course/src/main/java/in/testpress/course/network/TestpressCourseApiClient.java
course/src/main/java/in/testpress/course/ui/ContentActivity.java
course/src/main/java/in/testpress/course/ui/ExoPlayerActivity.java
course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java
course/src/test/java/in/testpress/course/util/ExoPlayerUtilTest.java

- Sent watched time range to the server on video attempt update
- Use `startPosition` field in all the places as `float` since server gives & gets
as `float` and convert to `long` only on get/set in the player.
- To calculate video watched duration in server

Send watched time range to server on video attempt update

---

core/build.gradle
core/src/main/java/in/testpress/core/TestpressUserDetails.java
core/src/main/java/in/testpress/ui/BaseToolBarActivity.java
core/src/test/java/in/testpress/ui/BaseToolBarActivityTest.java
course/src/main/java/in/testpress/course/ui/ContentActivity.java
course/src/test/java/in/testpress/course/ui/ContentActivityTest.java

- Cancel async network loading on activity destroy.
- To fix video playing after backpress due to incomplete network load.

Fix video playing after backpress due to incomplete network load.

---

.travis.yml
build.gradle
core/src/main/java/in/testpress/ui/BaseFragment.java
core/src/main/java/in/testpress/ui/BaseGridFragment.java
core/src/main/java/in/testpress/ui/BaseListViewFragment.java
core/src/main/java/in/testpress/ui/BaseToolBarActivity.java
core/src/main/java/in/testpress/util/CommonTestUtils.java
core/src/test/java/in/testpress/ui/BaseFragmentTest.java
course/src/main/java/in/testpress/course/ui/ChapterDetailActivity.java
course/src/main/java/in/testpress/course/ui/LeaderboardFragment.java
course/src/main/java/in/testpress/course/ui/TargetThreadFragment.java
course/src/test/java/in/testpress/course/ui/ChapterDetailActivityTest.java
course/src/test/java/in/testpress/course/ui/LeaderboardFragmentTest.java
course/src/test/java/in/testpress/course/ui/TargetThreadFragmentTest.java
exam/src/main/java/in/testpress/exam/ui/AccessCodeFragment.java
exam/src/main/java/in/testpress/exam/ui/AnalyticsFragment.java
exam/src/main/java/in/testpress/exam/ui/AttemptsActivity.java
exam/src/main/java/in/testpress/exam/ui/BookmarksActivity.java
exam/src/main/java/in/testpress/exam/ui/BookmarksFragment.java
exam/src/main/java/in/testpress/exam/ui/ReviewQuestionsActivity.java
exam/src/main/java/in/testpress/exam/ui/ReviewStatsFragment.java
exam/src/main/java/in/testpress/exam/ui/SearchFragment.java
exam/src/main/java/in/testpress/exam/ui/TimeAnalyticsActivity.java
exam/src/test/java/in/testpress/exam/ui/AccessCodeFragmentTest.java
exam/src/test/java/in/testpress/exam/ui/AttemptActivityTest.java
exam/src/test/java/in/testpress/exam/ui/BookmarksActivityTest.java
exam/src/test/java/in/testpress/exam/ui/BookmarksFragmentTest.java
exam/src/test/java/in/testpress/exam/ui/ReviewQuestionsActivityTest.java
exam/src/test/java/in/testpress/exam/ui/ReviewStatsFragmentTest.java
exam/src/test/java/in/testpress/exam/ui/TimeAnalyticsActivityTest.java

- Canceled network loads on activity/fragment destroy
- There is no meaning on performing network load after activity/fragment destroy.

Cancel network loads on activity/fragment destroy

---

core/src/main/java/in/testpress/models/greendao/Attempt.java
core/src/main/java/in/testpress/ui/BaseFragment.java
core/src/main/java/in/testpress/util/CommonTestUtils.java
core/src/main/java/in/testpress/util/CommonUtils.java
core/src/test/java/in/testpress/ui/BaseFragmentTest.java
core/src/test/java/in/testpress/ui/BaseToolBarActivityTest.java
core/src/test/java/in/testpress/util/CommonUtilsTest.java
exam/build.gradle
exam/src/main/AndroidManifest.xml
exam/src/main/java/in/testpress/exam/models/AttemptItem.java
exam/src/main/java/in/testpress/exam/models/Permission.java
exam/src/main/java/in/testpress/exam/ui/TestActivity.java
exam/src/main/java/in/testpress/exam/ui/TestFragment.java
exam/src/main/res/values/strings.xml
exam/src/main/res/values/styles.xml
exam/src/test/java/in/testpress/exam/ui/TestActivityTest.java
exam/src/test/java/in/testpress/exam/ui/TestFragmentTest.java

- Canceled network loads on `TestActivity` & `TestFragment` destroy.
- If an app was moved to background during attempting a test, returning to the app was not resuming. It was taking it to start exam screen. This is now fixed.
- Paused timer after 1 minute of the app went background(To handle user expected behaviour) and Shown "Exam paused click resume to continue" dialog to call start attempt API to update heartbeat on the server.
- Performing network load after destroy is unnecessary.

Cancel network loads on TestActivity destroy & Support activity recreate

---

core/src/main/java/in/testpress/models/InstituteSettings.java
exam/src/androidTest/java/in/testpress/exam/ui/ReviewStatsActivityTest.java
exam/src/main/java/in/testpress/exam/ui/ReviewStatsFragment.java
samples/src/main/java/in/testpress/samples/course/CourseSampleActivity.java

- Added isanalytics disabled field in institute settings.
- Made exam analytics visible on the basis of institute settings. 
- Earlier on making analytics disabled from the server side, was not affecting the app side analytics visibility.

Make exam analytics to appear on the basis of institute settings.

---

course/build.gradle
course/src/main/java/in/testpress/course/ui/WebViewActivity.java
course/src/test/java/in/testpress/course/ui/WebViewActivityTest.java

- Add support to clear cookies for webview
- Sometimes previous SSO session's cookies will be persisted
Fixes #98 
Testcases - 1

Add support to clear cookies for webview

---

core/src/main/java/in/testpress/ui/UserDevicesActivity.java
core/src/main/res/values/strings.xml
core/src/test/java/in/testpress/ui/UserDevicesActivityTest.java

- Changed info text in UserDevicesActivity to display lockout limit
- Earlier it used to display parallel login limit which wasn't useful.
TestCases - 1

Change info text in UserDevicesActivity

---

store/src/main/res/layout/testpress_products_list_item.xml

- Fixed width of product price string
- Used wrap_content for product_price, categories, counts so that their width depends on the content instead of product title like it was earlier.

Fix width of product price string

---

course/src/main/java/in/testpress/course/TestpressCourse.java
course/src/main/java/in/testpress/course/ui/CourseListActivity.java
course/src/main/java/in/testpress/course/ui/MyCoursesFragment.java

- Renamed `CourseListFragment` to `MyCoursesFragment`
- Since only user's courses are displayed in CourseListFragment and for course payment feature we need a top-level fragment that shows user's courses and available courses.We can name that top-level fragment as `CourseListFragment` so appropriate name for current `CourseListFragment` is `MyCoursesFragment`

Rename course list fragment to my courses fragment

---

core/src/main/java/in/testpress/core/TestpressException.java
course/build.gradle
course/src/main/java/in/testpress/course/ui/fragments/EmptyViewFragment.kt
course/src/test/java/in/testpress/course/fragments/EmptyViewFragmentTest.kt

- Added fragment to display error/exception
- This can be reused in any activity/fragment to handle the exception.
- This will reduce redundant code.
No of test cases - 5

Add fragment to display exception

---

course/src/main/java/in/testpress/course/repository/NetworkBoundResource.kt
course/src/test/java/in/testpress/course/repository/NetworkBoundResourceTest.kt

- While making requests if any exception occurs, it should be set to live data in Network bound resource.
- Previously it used to crash the app since the exception wasn't handled
No of test case - 1

Handle exception in network bound resource

---

course/src/main/java/in/testpress/course/di/InjectorUtils.kt
course/src/main/java/in/testpress/course/repository/ContentRepository.kt
course/src/test/java/in/testpress/course/repository/ContentRepositoryTest.kt

- After fetching content, content and its related items should be stored in DB
No of test case - 1

Add method to store content and its relations in repository

---

exam/src/main/java/in/testpress/exam/ui/TestActivity.java
exam/src/main/res/layout/testpress_exam_details_layout.xml

- If the exam has variable marks then the exam's total marks should not be displayed in the exam start screen.

Hide marks in exam if it has variable marks

---

exam/src/main/java/in/testpress/exam/ui/TestFragment.java

- After starting the exam, we can view the list of questions in the sidebar.
- Whenever a user answers a question or marks it for review, then in sidebar questions list appropriate color will be shown
- But the user may not get which color is for which type. So we need to show legends on top of the questions list.

Show legends in exam question filter menu

---

exam/src/main/java/in/testpress/exam/ui/ReviewStatsFragment.java
exam/src/main/res/layout/testpress_fragment_review_stats.xml

- If show score is disabled for an exam then the student cannot view analytics, so it is appropriate to hide it

Show analytics button only if show analytics is enabled

---

exam/src/main/java/in/testpress/exam/ui/PlainSpinnerItemAdapter.java
exam/src/main/java/in/testpress/exam/ui/TestFragment.java
exam/src/main/res/layout/testpress_plain_spinner_item.xml

- If exam sections have instructions then near the section title, the button will be displayed.
- On clicking, that button will display section's instructions

Add support to show sectional instruction for exam

---

core/src/main/java/in/testpress/models/InstituteSettings.java
core/src/main/java/in/testpress/ui/BaseToolBarActivity.java
core/src/main/res/layout/testpress_toolbar.xml

- Added a helper in the base activity to display a logo in the toolbar
- This can be used by the derived activities for displaying an image in toolbar which is usually logo
- This will be a prerequisite for the ReviewQuestionsActivity where we will be using to display the logo in the toolbar
- Helps in marketing when users share screenshots of the app screen

Expose method in base activity to display logo in toolbar

---

course/src/main/java/in/testpress/course/fragments/ExamContentFragment.kt
course/src/main/java/in/testpress/course/ui/ContentActivity.java

- If exam is paused, exam content should be refreshed(as its pausedattemptcount will be incremented).
- Previously exam content was not refreshed so paused attempt count will be 0 which caused it to display the start button instead of a resume button

Fix start button not working after pausing exam

---

core/src/main/assets/TestpressReview.js
core/src/main/java/in/testpress/util/WebViewUtils.java
exam/src/main/java/in/testpress/exam/ui/ReviewQuestionsFragment.java

- Once webview is loaded, img tag with logo URL will be added to it and it is hidden by default.
- Now once the user clicks the share button already loaded hidden image will be displayed while taking a screenshot and then hidden again.

Preload logo for share in review questions activity

---

course/src/main/java/in/testpress/course/network/NetworkStreams.kt
course/src/main/java/in/testpress/course/repository/ContentRepository.kt

- If content detail fragment is accessed directly, then it will fetch that content detail and store that content and its relations in DB. But streams are not being stored.
- So the video is playing in the original resolution
- This is fixed by storing streams

Fix Video is not playing with transcoded URL

---

core/src/main/assets/TestpressImageTagHandler.js

- In review questions, clicking image is not opening it.

Fix image click not working in review questions

---

core/src/main/res/layout/course_preview_layout.xml
course/src/main/java/in/testpress/course/ui/ChaptersListFragment.java
course/src/main/java/in/testpress/course/ui/CoursePreviewFragment.java
course/src/main/java/in/testpress/course/util/ProductUtils.kt
course/src/main/java/in/testpress/course/util/UIUtils.kt
course/src/main/res/values/strings.xml
course/src/test/java/in/testpress/course/util/ProductUtilsTest.kt

- In course products/store to buy a product, a user has to click course and navigate to premium content and then click it.
- The above process is time-consuming, so buy now button is added to the bottom of the course/chapter/contents list in product preview.

Add buy now button in product preview

---

core/src/main/assets/TestpressReview.js
core/src/main/assets/testpress_questions_typebase.css

- Rotated watermark such that logo's start will come at bottom left and will end at top right
- Since the above changes can be done for both review and attempt questions with single CSS class itself, `review-watermark` class is removed

Turn watermark upside down in review and attempt

---

course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java

- User's email address will be shown in marquee animation in exoplayer
- During first time, the user's email address will not be available so we will fetch it and then initialize view and then start marquee animation.
- When orientation is changed, we will again start marquee animation as it will be stopped. But if orientation is changed before fetching user details, then view won't be initialized so trying to start marquee animation will result in error

Fix NullPointerException in email marquee in exoplayer

---

course/src/main/java/in/testpress/course/ui/ChapterDetailActivity.java
course/src/main/java/in/testpress/course/ui/ContentsListFragment.java

- Earlier on clicking the chapter, we will fetch chapter detail to know if that chapter has children or content.
- But now as we get all chapters of those courses including children in chapters list itself we don't need to fetch chapter detail page. We can simply conclude that if the chapter has children then we should show sub-chapters or else we should show contents list.

Remove fetching chapter detail API from chapters list screen

---

course/src/main/java/in/testpress/course/fragments/QuizAttemptsList.kt
course/src/main/res/layout/quiz_attempts_list_view.xml

- Problem is for exam we will show either start screen or attempts list screen. And both these screens will have start button. So we have BaseExamWidgetFragment which will have a start button. Exam Start screen and exam attempts screen will inherit from this BaseExamWidgetFragment.
- Now for the quiz we are going to show both start view and attempts list in same screen. So earlier we reused the exam attempts list and hidden the start button alone.
- But as logic to display attempts list is very small we can write separate quiz attempts list instead of reusing exams attempts list and hiding start button
- This was it will be more straight forward.

Refactor quiz attempts list

---

course/src/main/java/in/testpress/course/repository/QuizExamRepository.kt

- To make quiz exams offline first, when an exception occurs we will use or create a local attempt.
- But we should use or create local attempt only for network error.
- All other exceptions should be handled

Fix paid quiz can be taken without purchase

---

exam/src/main/java/in/testpress/exam/ui/ReviewStatsFragment.java

- Earlier view binding was done in onCreateView.
- So it was moved to bindViews method as per our convention and it is called in onViewCreated

Move view bind to separate method in review stats fragment

---

course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java
course/src/main/java/in/testpress/course/util/TrackSelectionDialog.kt

Right now track selection dialog box can be used only by the player, but for downloading also we need track selection dialog box
The Download APIs of ExoPlayer won't expose TrackSelection handle. They only give the parameters and mappedTrackInfo
So instead of passing trackselector we can pass only parameters and mappedTrackinfo to Track Selection Dialog.
In addition to this, the On click of track selection box is changed as an interface. This is done so that upper layer can implement it as per requirements.

Make track selection dialog reusable for both player and download

---

course/src/main/java/in/testpress/course/fragments/VideoContentFragment.kt
course/src/main/java/in/testpress/course/helpers/DownloadTask.kt
course/src/main/java/in/testpress/course/helpers/VideoDownloadMonitor.kt
course/src/main/java/in/testpress/course/repository/OfflineVideoRepository.kt
course/src/main/java/in/testpress/course/services/VideoDownloadService.kt

- The download model provided by exoplayer don't store video details like thumbnail, description, title. It will only have download url, percentage, bytes downloaded
- So Whenever the new download is started, progressing or removed it should be updated in OfflineVideo model of ours.
- This way we can use OfflineVideo model to show download details or we can observe it to show progress.

Add support to update download details to offline video

---

core/src/main/java/in/testpress/database/OfflineVideo.kt
core/src/main/java/in/testpress/database/Room.kt
course/src/main/java/in/testpress/course/domain/DomainOfflineVideo.kt
course/src/main/java/in/testpress/course/fragments/DownloadsFragment.kt
course/src/main/java/in/testpress/course/helpers/DownloadTask.kt
course/src/main/java/in/testpress/course/helpers/DownloadedVideoRemoveHandler.kt

-  If a user downloads a video and after that, if his access for that course is revoked then the video should be deleted
- So we delete videos whose course id is not present in course list of local db

Remove downloaded videos for which course is not present

---

core/build.gradle
core/src/main/java/in/testpress/network/NetworkBoundResource.kt
course/build.gradle
course/src/main/java/in/testpress/course/repository/ContentRepository.kt
course/src/test/java/in/testpress/course/repository/NetworkBoundResourceTest.kt

- Moved NetworkBoundResource to Core
- Added Coroutine dependency in Core
- NetworkBoundResource is used in both course and store so if NetworkBoundResource is in Core we can avoid file duplication

Move NetworkBoundResource to core

---

course/src/main/java/in/testpress/course/fragments/ContentBottomNavigationFragment.kt
course/src/test/java/in/testpress/course/fragments/ContentBottomNavigationFragmentTest.kt

- Next/Prev button in bottom navigation should skip locked/scheduled content
No of test cases - 4

Fix locked and scheduled content accessible from bottom navigation

---

course/src/main/java/in/testpress/course/fragments/AttachmentContentFragment.kt
course/src/main/java/in/testpress/course/fragments/BaseContentDetailFragment.kt

- Attachment URL will be valid only for some time (5 mins in our case). So when the user tries to download the attachment after URL expiry it will show access denied.
- Solution is to fetch the attachment URL whenever the user clicks the download button and use that attachment URL.

Fix access denied error on downloading attachment content 

---

course/src/main/java/in/testpress/course/fragments/VideoContentFragment.kt

- In some devices, menu is cleared before being initialized.
- Clearing menu before being initialized leads to app crash.

Fix App crash on opening the video

---

course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java

- Issue: The broadcast receiver is unregistered before even registering
- The receiver is registered when we are in the onStart. onPause is called at the time user receive phone call, so there the receiver is unregistered. When phone call ended onResume is been called and while closing the activity again we are trying to unregister the receiver where it already been unregistered. [ref](https://stackoverflow.com/a/28778985/12883471)
- This issue is fixed by wrapping it in a try-catch block so when the receiver is not registered and we try to unregister we are catching it in the catch [ref](https://stackoverflow.com/a/36530677/12883471)

Fix Exoplayer crash on app crash

---

exam/src/main/res/layout/content_list_item.xml
exam/src/main/res/layout/exam_content_list_item.xml

- In  [747530c2](https://github.com/testpress/android-sdk/commit/747530c2645e3e2ebf8c67512c7d2d434e99ea0e) the scheduled info is been wrapped in the content detail layout. when the content is scheduled we are not showing the content details hence the schedule info is also being hidden.
- Solution: We have moved the scheduled info from content details layout

Fix: Title should be visible for scheduled content

---

course/src/main/java/in/testpress/course/helpers/DownloadTask.kt

Recently the course content api has changed. Now video thumbnails are exposed 
in content instead of video.

Display Thumbnail for offline videos

---

course/src/main/res/layout/downloaded_video_list_item.xml

when the downloaded video title is long, the title is overlapped with delete menu icon, So added layout weight to avoid overlapping

Fix: Title overlap with delete downloaded video menu icon

---

course/src/main/java/in/testpress/course/ui/VideoDownloadQualityChooserDialog.kt

- We have used progress bar in video download chooser dialog to show loading 
- This Progressbar is hidden on clossing the dialog box
- The issue is we are trying to close the progressbar before its being initialized.
- This is handled by checking if progressbar is null before closing the dialog.

Fix App crash on opening and quickly closing the download chooser dialog

---

course/src/main/java/in/testpress/course/ui/VideoDownloadQualityChooserDialog.kt

- We have used = video download chooser dialog to select resolution to download video
- on Clicking ok button will request to download video and dismiss the dialog
- The issue is if the user clicks the ok button before the download is prepared. The download request will throw exception, this cause app crash
- This is handled by checking if the tack selection is initialized before building a download request

Fix App crash on downloading video

---

course/src/main/java/in/testpress/course/fragments/DocumentViewerFragment.kt

- Issue is we are not creating content attempt for pdf, so next content is not getting unlocked when progressive lock is enabled.

Fix next content not opening after pdf if progressive lock is on

---

core/src/main/java/in/testpress/core/TestpressSDKDatabase.java
core/src/main/java/in/testpress/models/greendao/CourseAttempt.java
exam/src/test/java/in/testpress/exam/ui/SaveAttemptSectionTest.kt
exam/src/test/java/in/testpress/exam/ui/ShareToUnlockActivityTest.kt

- The issue is the section is not stored in the DB when we start the exam.
- So when we resume an exam the section will be null.
- This is fixed by storing the sections in DB

Fix Sectional Time Duration Lock is not working while resume the exam

---

course/src/main/java/in/testpress/course/fragments/BaseContentDetailFragment.kt
course/src/main/java/in/testpress/course/ui/ContentActivity.java
course/src/test/java/in/testpress/course/fragments/BaseContentDetailFragmentTest.kt

- Issue is if progressive lock is enabled and if user completes a content then on clicking back next content is not unlocked.
- Another Issue is attempted tick is not displayed when an user views a content detail and goes back.
- So to solve this content list is refetched in the background once the user presses back button from content detail

Refresh contents list on back press from content detail

---

course/src/main/java/in/testpress/course/ui/ZoomMeetActivity.kt

- Issue is sometimes zoom live class can be recorded.
- This is because screen recording disabling should be done before setting content view.
- So instead of onCreate screen record disabling is done in setContentView

Fix zoom live class can be recorded randomnly bug

---

core/src/main/java/in/testpress/util/TimeUtils.kt
course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java
course/src/main/java/in/testpress/course/util/ExoplayerAnalyticsListener.kt

- Issue is if user moves forward then we send only that duration data to server but since API is throttled server may discard it. So only some watch duration will be stored in server.
- Solution is to send all watch duration data to server.
- This is done by listening to player seek events and storing all watch duration data. Once user presses back button/seek/play/pause all the stored watch duration will be sent to server

Fix incorrect video watch duration update to API

---

course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java

- We are storing video watched progress whenever user seeks video, but we are not doing it when user presses back button.
- So video watched progress is not getting updated when back button is pressed.

Fix video watched progress not updated when user presses back button

---

course/src/main/java/in/testpress/course/domain/DomainContent.kt
course/src/main/java/in/testpress/course/domain/DomainExamContent.kt
course/src/main/java/in/testpress/course/fragments/BaseExamWidgetFragment.kt

- Issue is start button is not displayed for shallow cloned exams. This happens when user attempts one of the clone and if user tries to attend the another clone then start button won't be displayed. This is because user already has attempted the exam.
- This issue is fixed by considering attempt count of chapter content instead of exam

Fix start button not displayed for shallow cloned exams

---

course/src/main/java/in/testpress/course/fragments/VideoConferenceFragment.kt

- Handled `NoClassDefFoundError` while opening zoom meeting on Non-zoom enabled app.
- Zoom plugin may or may not be enabled on app. So while invoking the method to open zoom meeting, if the plugin was not added, then it make the app crash by throwing `NoClassDefFoundError`. So handled this error in SDK side by displaying the appropriate toast message.

Fix App crash while opening zoom meetings on non-zoom ingrated app

---

course/src/main/java/in/testpress/course/fragments/ExamStartScreenFragment.kt
course/src/main/res/drawable/ic_baseline_info_24.xml
exam/src/main/res/layout-xlarge/testpress_exam_details_layout.xml
exam/src/main/res/layout/testpress_exam_details_layout.xml

- Exam start screen will let the user know whether the exam is ended or not by a description message at the bottom of the screen.
- Previously, even if the exam was ended, an "All the Best" description message was displayed on the UI which confused the users. So the description message was changed to "The Exam was ended" if the exam was ended.

Fix exam ended status message

---

course/src/main/java/in/testpress/course/helpers/DownloadTask.kt

- Added a null check on duration field of Offline video in DownloadTask and assigned "0" if the duration is null.
- `NullPointerException` was thrown as we were assigning null to duration field of OfflineVideo.

Add null check for video duration in DownloadTask

---

course/src/main/java/in/testpress/course/ui/VideoDownloadQualityChooserDialog.kt

- **Issue:** the hideProgressbar method is being called after the view being destroyed.
- Since the Exoplayer video download handler is asynchronous even though, When user clicks on the download button and before loading the download dialog box if the user came out of that activity, the hideProgress is being called by the Exoplayer video download handler.
**Fix:** Need to hide the progress bar only when the view is visible

Fix App crash on Clicking download button

---

exam/src/main/java/in/testpress/exam/ui/TestFragment.java

- Stopped the progress bar after displaying maximum questions attempted
- As user ends the exam attending with more than maximum number of questions, this progress dialog will be shown, but its not dismissed. So the user could not end the exam.

Fix exam not ending when maximum number of questions given

---

core/build.gradle
course/build.gradle
exam/build.gradle
gradle.properties
gradle/gradle-mvn-github-packages.gradle
store/build.gradle

- As Bintray is closed, we were using jitpack.io for artifact repository. But we need to manually build and upload artifacts there which is repetitive process.  
- So We moved to github packages to automatically upload artificats

Add support to publish package to github packages

---

course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java

- If user watches video fully without pausing or fast forwarding video, then video watch status is not getting updated.

Fix video status not updated if user didn't pause or skip video

---

core/src/main/assets/TestpressTestEngine.js
core/src/main/assets/testpress_questions_typebase.css
core/src/main/java/in/testpress/models/FileDetails.java
core/src/main/java/in/testpress/util/Misc.kt
core/src/main/java/in/testpress/util/ProgressDialog.kt
core/src/main/res/layout/custom_progress_dialog.xml
exam/build.gradle
exam/src/main/java/in/testpress/exam/api/TestpressExamApiClient.java
exam/src/main/java/in/testpress/exam/models/AttemptItem.java
exam/src/main/java/in/testpress/exam/models/UserUploadedFile.kt
exam/src/main/java/in/testpress/exam/ui/TestActivity.java
exam/src/main/java/in/testpress/exam/ui/TestFragment.java
exam/src/main/java/in/testpress/exam/ui/TestQuestionFragment.java

- Used PickiT library to handle file picking support. Picked files will be uploaded to testpress and then its path will be stored in attempt item.
- Once user presses next or pauses or ends exam. File paths from attempt item will be stored in backend.

Add file type question support

---

course/src/main/java/in/testpress/course/fragments/VideoContentFragment.kt
course/src/main/java/in/testpress/course/util/DateUtils.kt

- Previously we were supporting only HH:MM:SS
- Modified regex to support the following
- HH:MM:SS	
- H:MM:SS
- MM:SS
- M:SS

fix: H:MM:SS duration string is not clickable in video

---

store/src/main/java/in/testpress/store/payu/PayuPaymentGateway.kt

- This issue raises in institutes with custom payment, while users try to purchase a package from the store using the card, the app shows the Payment failure page because Payu raises an error `Card can not be stored! user_credentials is missing!`.
- This is fixed by passing the user credentials parameter to PayUCheckoutPro open function.

fix: Not able to purchase course from store Using Card Payment

---

course/src/main/java/in/testpress/course/ui/CourseListActivity.java
course/src/main/java/in/testpress/course/ui/CourseListFragment.java
store/src/main/java/in/testpress/store/TestpressStore.java
store/src/main/java/in/testpress/store/ui/OrderConfirmActivity.java
store/src/main/java/in/testpress/store/ui/PaymentFailureActivity.kt
store/src/main/java/in/testpress/store/ui/ProductDetailsActivity.java

- Issue is, that the Goto home button on the payment success page was not redirecting the user to learn tab on click. 
- It's because we haven't called the finish method in the PaymentSucessActivity result. which is why it's showing the product detail page on the button click.
- This is fixed by calling the finish method on the PaymentSucessActivity result and redirecting the user to learn tab and refreshing the course on the CourseListActivity onActivityResult if the request code is Testpress store request code and the continue purchase flag is false.

fix: Fix home button on payment success page not redirecting to learn tab

---

course/src/main/java/in/testpress/course/helpers/DownloadTask.kt
course/src/main/java/in/testpress/course/helpers/VideoDownloadManager.kt
course/src/main/java/in/testpress/course/helpers/VideoDownloadRequestCreationHandler.kt
course/src/main/java/in/testpress/course/services/VideoDownloadService.kt
course/src/main/java/in/testpress/course/ui/VideoDownloadQualityChooserDialog.kt
course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java
course/src/main/java/in/testpress/course/util/OfflineDRMLicenseHelper.kt
course/src/main/java/in/testpress/course/util/VideoUtils.kt
course/src/main/res/values/strings.xml

- When user downloads a video, we will initially download widevine key and store it in video download request.
- If license expires, we will again download the license and store it in download request.

Add support to download DRM protected video

---

exam/src/main/java/in/testpress/exam/ui/ExamInstructions.kt
exam/src/main/res/layout/fragment_test_instructions.xml

- Issue is images in exam instruction are not visible in the instruction tab instead it's showing a square box with a green background for an image, 
- This is fixed by using the Webview for showing instructions.

fix: Fix images in exam instruction not visible

---

exam/src/main/java/in/testpress/exam/ui/ExamInstructions.kt
exam/src/main/res/layout/fragment_test_instructions.xml

- If exam title is very big then it is displayed in multiple lines in Instructions screen.
- This is fixed by displaying "Instructions" instead of exam title in Instructions screen. We display exam title properly in previous screen so it need not to be displayed again.

fix: Fix exam title shows in multiple lines in instructions screen

---

core/src/main/java/in/testpress/util/FullScreenChromeClient.java

- Issue is embedded DRM-protected video not playing because we haven't provided the permission to webview to access protected media, 
- That permission was given to the webview in this commit.

fix: Add support to access embedded DRM-protected content

---

course/src/main/java/in/testpress/course/fragments/ContentLoadingFragment.kt

- This reverts commit b3e4ccb631d56971c6fcc21f378dec2b8168a788.
- Because we planned to re-fetch locked content on the content loading page and show the error message from API on the permission denied page if the content is locked.

Revert " fix: Prevent viewing locked content on notification redirection #422"

---

core/src/main/java/in/testpress/network/NetworkBoundResource.kt
course/src/main/java/in/testpress/course/fragments/ContentLoadingFragment.kt

- Re-fetched locked content on the content loading page, showed permission denied message if the content is locked.

fix: Refetch locked content on content loading page

---

core/build.gradle
core/src/main/java/in/testpress/ui/fragments/DiscussionFragment.kt
course/build.gradle
course/src/main/java/in/testpress/course/fragments/DocumentViewerFragment.kt
course/src/main/java/in/testpress/course/ui/PdfViewerActivity.kt
course/src/main/java/in/testpress/course/ui/VideoDownloadQualityChooserDialog.kt
course/src/main/java/in/testpress/course/ui/WebViewWithSSO.kt
course/src/main/java/in/testpress/course/util/TrackSelectionDialog.kt
exam/build.gradle
exam/src/main/java/in/testpress/exam/ui/ReviewPanelAdapter.kt
exam/src/main/java/in/testpress/exam/ui/adapters/ShareToUnlockAdapter.kt
store/build.gradle

- Kotlin synthetics binding is depreciated. So we are migrating to jetbrains view binding
- Reference: https://developer.android.com/topic/libraries/view-binding/migration#groovy

refactor: Migrate from Kotlin synthetics to Jetpack view binding

---

course/src/main/java/in/testpress/course/helpers/VideoDownloadRequestCreationHandler.kt

- We used the addTrackSelectionForSingleRenderer to select user-selected resolution tracks while downloading, but in that method, renderers were disabled except the video renderers. so the DRM contents were downloaded without audio tracks.
- This is fixed by selecting tracks to download without using that method.

fix: Audio not available for downloaded DRM content

---

build.gradle
course/src/main/java/in/testpress/course/services/VideoDownloadService.kt
course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java
course/src/main/java/in/testpress/course/util/ZoomMeetHandler.kt
mobilertc/build.gradle

-  update Zoom sdk version to 5.11.0.6883
-  update exoplayer version to 2.16.1
-  replaced deprecate method 
-  Zoom sdk version using exoplayer version 2.16.1 
- Android version 12 need zoom sdk version 5.11.0.6883
Fixes # .

Update zoom sdk version to 5.11.0.6883

---

course/src/main/java/in/testpress/course/util/VideoPlayerInterceptor.kt

-  Generate a new URL for getting the video encryption key using institute settings
-  If the Institute subdomain will change video encryption key request will fail
Fixes # .

fix: Get video encryption key with current institute subdomain

---

course/src/main/java/in/testpress/course/ui/viewholders/ExamContentListItemViewHolder.kt
course/src/main/java/in/testpress/course/ui/viewholders/VideoContentListItemViewHolder.kt
exam/src/main/res/layout/exam_content_list_item.xml

-  Hide exam duration and question count if the exam null
-  Hide video duration if video null
-  Previously question count and duration for non preview content were shown as placeholder
Fixes # .

fix: Removed fallback question count and duration

---

exam/src/main/java/in/testpress/exam/ui/TestFragment.java

-  Allow fetching all questions when the exam has no sectional lock
- previously we are allowing all question fetching for the IBPS template only that is the reason for the section getting duplicates for all other templates.
Fixes #.

fix: Sections are getting duplicated

---

exam/src/main/java/in/testpress/exam/ui/TestFragment.java
exam/src/main/java/in/testpress/exam/ui/TestQuestionFragment.java
exam/src/main/java/in/testpress/exam/ui/TestQuestionPagerAdapter.java

- Right now, in exam questions page only variable marks is displayed.
- If variable marks is disabled, exam marks should be displayed. This is fixed in this PR

fix: Fix incorrect marks displayed in questions

---

course/src/main/java/in/testpress/course/util/ZoomMeetHandler.kt

-  Hide zoom meeting URL - (Ref [link](https://devforum.zoom.us/t/how-to-hide-invite-link-in-title-bar-top-bar/72554/4))
-  User can able to copy and share zoom link 
Fixes #.

fix: User can able to share zoom link

---

course/src/main/java/in/testpress/course/fragments/NativeVideoWidgetFragment.kt

-  Added validation for attempt objectId
-  If object id is null assign objectId as -1
-  After attending the zoom meeting user was not able to view the recorded video because of attempt objectId was null
-  In API v2.3/contents/{Content.Id}/attempts/ its return attempt object as null if the content type is video conference
Fixes #.

fix: App crash while open zoom recorded video

---

course/src/main/res/layout/available_course_fragment.xml

- Used marginPadding and clipToPadding attributes to hide margin while scrolling the recyclerView
- Previously we used margin for spacing
Fixes #.

fix: Margin spacing in productCategories listView

---

course/src/main/java/in/testpress/course/repository/ProductCategoriesRepository.kt

- Fetching DB should not be done in the main thread. (ref - [link](https://developer.android.com/reference/android/arch/persistence/room/RoomDatabase.Builder#allowmainthreadqueries))
- In getAllProductCategories() we are fetching DB in the main thread which leads to an app crash.
- This happens only when the device is offline. If the device is online we call this getAllProductCategories() inside the CoroutineScope
-  Calling this getAllProductCategories() in the background thread using (Dispatchers.IO) will fix this issue

fix: App crashes while opening when the device is offline

---

exam/src/main/java/in/testpress/exam/ui/TestFragment.java

- Students facing API failure while attending the exam but we can't able find the type of failure. 
- Right now, we are showing an alert box whenever an API failure occurs, so adding the API error code to the alert message will allow us to find the type of failure.

fix: Add error code in Alert dialog box

---

core/src/main/java/in/testpress/database/Room.kt
core/src/main/java/in/testpress/database/dao/ContentLiteDao.kt
core/src/main/java/in/testpress/database/dao/ContentLiteRemoteKeyDao.kt
core/src/main/java/in/testpress/database/entities/ContentEntityLite.kt
core/src/main/java/in/testpress/database/entities/ContentEntityLiteRemoteKey.kt
core/src/main/java/in/testpress/database/entities/RunningContentEntity.kt
course/src/main/java/in/testpress/course/domain/DomainContent.kt
course/src/main/java/in/testpress/course/fragments/RunningContentListFragment.kt
course/src/main/java/in/testpress/course/network/CourseService.kt
course/src/main/java/in/testpress/course/pagination/RunningContentRemoteMediator.kt
course/src/main/java/in/testpress/course/repository/RunningContentsRepository.kt

- Previously we have separate model classes for running and upcoming
- Running and upcoming are the same response so we use a common class for both

refactor: Rename RunningContent to ContentEntityLite

---

course/src/main/java/in/testpress/course/ui/ChapterDetailActivity.java
course/src/main/java/in/testpress/course/ui/CourseDetailsTabAdapter.java

- Fragments are currently initialized directly inside the CourseDetailsTabAdapter.
- To add more fragments, we need to modify the adapter class.
- By passing the fragment list as an argument to the adapter, we can add multiple fragments from outside the adapter.
- We removed an unused argument from the CourseDetailsTabAdapter.

refactor: Extract fragment initialization in CourseDetailsTabAdapter

---

course/src/main/java/in/testpress/course/util/DateUtils.kt
course/src/main/res/values/strings.xml

In order to simplify and generalize the plurals resource strings used for a time duration, the existing resource strings for minutes, hours, days, months, and years were refactored into a single plurals resource string with a placeholder for the time unit. The new resource string is named "time_duration" and includes two placeholders for the quantity and the time unit. This change simplifies the code and makes it easier to add new time units in the future.

refactor: Plural strings in DateUtil

---

core/src/main/java/in/testpress/util/DateUtils.kt
core/src/main/res/values/strings.xml
course/src/main/java/in/testpress/course/adapter/viewholder/RunningContentItemViewHolder.kt
course/src/main/java/in/testpress/course/adapter/viewholder/UpcomingContentItemViewHolder.kt
course/src/main/java/in/testpress/course/fragments/DownloadsFragment.kt
course/src/main/java/in/testpress/course/fragments/VideoContentFragment.kt
course/src/main/java/in/testpress/course/helpers/CourseLastSyncedDate.kt
course/src/main/res/values/strings.xml

- Beforehand, DateUtil was included in the course library which made it unavailable for usage in the exam library due to the lack of dependency.
- By transitioning to the core library, we can benefit from the availability of all libraries since every library relies on the core library.

refactor: Move the DateUtil file to the Core library

---

course/src/main/java/in/testpress/course/adapter/CourseContentListAdapter .kt
course/src/main/java/in/testpress/course/domain/DomainContent.kt
course/src/main/java/in/testpress/course/fragments/CourseContentListFragment .kt

In the past, we had separate models for running content and upcoming content, which necessitated the use of a generic type. However, now that we have a single model for both running and upcoming content, we no longer require a generic type.

refactor: Removed generic type parameter in CourseContentList

---

core/src/test/java/in/testpress/util/FileDownloaderTest.kt
course/src/main/java/in/testpress/course/fragments/AttachmentContentFragment.kt

- Before, we only allowed users to view attachment content, which required an internet connection.
- Some users had to use third-party apps to open attachments, but some of these apps did not have Internet permissions, so users could not open them.
- We have added a download option for attachment content so that users can download and open attachments using any third-party app.

fix: Add Download Option for Attachment Content

---

core/build.gradle
core/src/test/java/in/testpress/ui/EmptyViewFragmentTest.kt

- Refactoring EmptyViewFragmentTest to the core library as EmptyViewFragment.kt is located in the same library

refactor: Move EmptyViewFragmentTest to core library

---

course/src/main/java/in/testpress/course/ui/viewholders/VideoContentListItemViewHolder.kt

- Previously, the green tick was only shown if the video watch percentage was 100%. 
- Now display the green tick based on the user's attempt count field, which indicates whether they have attempted to watch the video.

fix: Green mark is not visible after watching the video completely

---

core/src/main/java/in/testpress/models/InstituteSettings.java
samples/src/main/java/in/testpress/samples/course/NavigationDrawerActivity.java

- Precisely Android SDK does know white labeled host URL
- In this commit, we add a white-labeled host URL field to the InstituteSetting model
- The purpose of this addition is to prevent the opening of non-institute URLs in our customized webview.

fix: Add field in InstituteSettingsModel

---

core/src/main/java/in/testpress/util/FileDownloadBroadcastReceiver.kt
core/src/main/java/in/testpress/util/PermissionsUtils.java

- For Android S+ (version 31) and above, it is recommended to include the FLAG_IMMUTABLE flag when creating a PendingIntent. 
- Refe - [link](https://developer.android.com/topic/security/risks/pending-intent#flag_immutable)

fix: Not able to Download Attachments in SDK version 30 above

---

core/src/main/java/in/testpress/util/PermissionsUtils.java

-  We previously implemented runtime permission handling for all SDK versions.
-  However, we have now optimized it to request the runtime storage permission (WRITE_EXTERNAL_STORAGE) only for SDK versions 23 to 29 (Android Marshmallow to Android 10)
- This change ensures that the app follows the appropriate permission model based on the specific SDK version, improving compatibility and enhancing the user experience by requesting permissions only when required.
- Ref [link](https://developer.android.com/reference/android/app/DownloadManager.Request#setDestinationInExternalPublicDir(java.lang.String,%20java.lang.String))

refactor: Update runtime storage permission check

---

core/src/main/java/in/testpress/util/FileDownloader.kt
core/src/main/java/in/testpress/util/StringUtils.kt

- We are not able to create a file with the following characters (<, >, :, ", /, \\, |, ?, *) because these are the reserved characters by OS
- In our case, Some Attachment titles may contain these characters for we are not able to download 
- In this commit replacing these characters with underscore

fix: Attachment not download when file name contain illegal characters

---

store/src/main/res/layout/testpress_product_details_layout.xml

- We forgot to add the toolbar layout to the XML file for the Product detail view, For an activity that extends BaseToolBarActivity to work correctly, the corresponding XML file must include a toolbar layout.
- If the toolbar view is missing, it will cause an exception because it is initialized in BaseToolBarActivity.
- so included the toolbar layout in the XML layout for the Product detail view, to fix the same.

fix: App crash while opening product detail page

---

exam/src/main/java/in/testpress/exam/ui/ReviewQuestionsActivity.java
exam/src/main/java/in/testpress/exam/ui/ReviewQuestionsFragment.java
exam/src/main/java/in/testpress/exam/ui/ReviewStatsFragment.java

- We are adding a new feature called custom test generation int this feature users can able attend exams without an exam object
- We have modified the review questions page to be accessible even without the exam object, ensuring that we have properly handled the exam object in all relevant sections.

fix: Add support to open ReviewQuestionPage Without Exam object

---

core/src/main/java/in/testpress/core/TestpressException.java
core/src/main/java/in/testpress/fragments/EmptyViewFragment.kt
core/src/test/java/in/testpress/ui/EmptyViewFragmentTest.kt

- This commit adds a new static method called httpError() in TestpressException class. This method allows creating a TestpressException object specifically for HTTP errors with a custom error code and error message.
- This new method enhances the flexibility of handling HTTP errors in the Testpress library.

fix: Add static method to TestpressException

---

course/src/main/java/in/testpress/course/ui/ChaptersListFragment.java

- Regrettably, we inadvertently neglected to remove an unused import statement in the ChaptersListFragment. However, in this commit, we are rectifying this issue by removing it.

fix: Build Fail

---

core/src/main/java/in/testpress/util/FileDownloadBroadcastReceiver.kt
core/src/main/java/in/testpress/util/StringUtils.kt

- In this commit #512, we implemented download support for attachments, and once the download is complete, a notification is displayed. We also added a pending intent to that notification. However, we encountered an issue where the pending intent only works for opening PDF files, while other file types cannot be opened.
- To address this problem, we made a commit that handles the differentiation between PDF files, image files, and other file types. If the downloaded file is a PDF, we open the PDF activity. If the downloaded file is an image, we open the image viewer activity. Otherwise, if it is any other file type, we open the download activity. This allows for the appropriate handling of different file types in the application.

fix: Add support to open Download activity

---

course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java

- Each time the user changes the resolution, we reset the previously chosen track and assign the newly selected track.
- But we are not doing this process when the user selects the Auto resolution option.
- In this commit, we clear the previously chosen track when the user selects Auto resolution.

fix: Auto resolution option not working in video

---

build.gradle
course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java

-  Update exoplayer library version to 2.17.1
- Updated Deprecated symbols EventListener -> Listener

fix: update exoplayer dependency

---

store/src/main/java/in/testpress/store/razorpay/RazorpayPaymentGateway.kt
store/src/main/java/in/testpress/store/ui/OrderConfirmActivity.java

- After successful payment, the in-app message was not being shown in razorpay payment.
- The reason was that according to razorpay docs, the success/ failure event handlers 
should be present inside the Activity, not the Fragment.
- Fixed by moving the methods to the activity.
- 
- 
Fixes # .

fix: Razorpay payment success/failure message not shown

---

core/src/main/java/in/testpress/fragments/WebViewFragment.kt
core/src/main/java/in/testpress/util/webview/CustomWebViewClient.kt

- We are currently displaying errors for each HTTP error that occurs. Due to the nature of using a WebView, various URLs are loaded, including static image URLs. If any of these static URLs encounter an error, we will also present the error within the WebView.
- However, in this particular commit, we are not addressing the issue of displaying errors for other URL failures such as those related to static image URLs.

fix: Add validation for WebView Http Error

---

core/src/main/java/in/testpress/network/TestpressApiClient.java
core/src/main/java/in/testpress/util/UserAgentProvider.java

- We include the application name in the User-Agent request header to identify the app usage. If the app name includes special characters, it leads to a crash because the header value should not contain non-ASCII values. https://github.com/square/okhttp/issues/891
- In this commit, we have passed the package name to the User-Agent instead of the App name because the package name is also unique.

fix: App crash when app name contains contain non-ASCII characters

---

store/src/main/java/in/testpress/store/razorpay/RazorpayPaymentGateway.kt

- After users purchase a product we redirect them to the success page because we added a redirect URL to RazorpayPaymentGateway
- By removing this redirect URL we can get a successful callback from RazorpayPaymentGateway and we show the success page from our app.

fix: Remove redirect URL from RazorpayPaymentGateway

---

course/src/main/java/in/testpress/course/ui/ChaptersListFragment.java

- We are using a chapter list view for the product preview page at the time we don't have the course object but we need the course object to show a custom test icon in the app bar. insufficient course object leads to an app crash.
- Also we don't want to show a custom test icon button on the product preview page.
- In this commit, we hide the custom test icon if the product slug has a value.

fix: Custom test icon is showing in product preview page

---

course/src/main/java/in/testpress/course/ui/QuizActivity.kt

- Previously we did not handle the onBackPress event.
- In this commit, we handled onBackPress() when the user pressed the back button we showed the exam end alert dialog.

fix: Unable to finish the quiz exam when the back button is pressed

---

course/src/main/java/in/testpress/course/network/CourseService.kt
course/src/main/java/in/testpress/course/network/NetworkContentAttempt.kt
course/src/main/java/in/testpress/course/repository/QuizExamRepository.kt
course/src/main/java/in/testpress/course/ui/QuizActivity.kt
course/src/main/java/in/testpress/course/viewmodels/QuizExamViewModel.kt

- In this commit d9a0b41 we end the ContentAttempt while ending the exam.
- After completing the Quiz exam, we conclude the ContentAttempt. During this process, we receive a success response for the ContentAttempt. However, our implementation is designed to handle an Attempt response, which results in our inability to properly parse the response, leading to inaccurate data being displayed on the Review page.
- In this commit we Handled success response for the ContentAttempt

fix: Review page showing incorrect data after complete the quiz exam

---

course/src/main/java/in/testpress/course/domain/DomainAttempt.kt
course/src/main/java/in/testpress/course/fragments/LoadingQuestionsFragment.kt
course/src/main/java/in/testpress/course/network/CourseService.kt
course/src/main/java/in/testpress/course/repository/QuizExamRepository.kt
course/src/main/java/in/testpress/course/ui/CustomTestGenerationActivity.kt
course/src/main/java/in/testpress/course/ui/QuizActivity.kt
course/src/main/java/in/testpress/course/viewmodels/QuizExamViewModel.kt
course/src/main/java/in/testpress/course/viewmodels/QuizViewModel.kt

- For the custom test generation feature we don't have exam or content objects we only have attempt ID.
- In this commit, we added support to take the exam with attempt ID in the Quiz Template.
- After obtaining the attempt ID for the webview, we initiate a user exam attempt, retrieve the exam questions, and commence the exam. Once the user completes the exam, we conclude the attempt and display the review page.

fix: Add support to take the exam with attempt ID in Quiz template

---

store/src/main/java/in/testpress/store/network/ProductService.java
store/src/main/java/in/testpress/store/network/StoreApiClient.java
store/src/main/java/in/testpress/store/ui/OrderConfirmActivity.java

- In this commit a159622 we removed the payment redirect URL.
- The issue of failed payment reconciliation not being triggered arises due to the removal of this URL.
- In this commit, we pass the `trigger_payment_reconciliation` field in the Order refresh API to trigger payment reconciliation for filed payments.

fix: Payment reconciliation is not taking place in the backend

---

course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java

- In this commit 4e963de we added pinch-to-zoom support we initialize this functionality when a player is initialized
- we initialize player on onStart() and onResume()
- When the user starts this video content activity in landscape mode this zoom functionality is invoked prior to its initialization. 
- Furthermore, in scenarios where apps transition from the background in landscape mode, this zoom functionality is invoked prior to its initialization. To address this, we have modified the code in this commit to initialize the pinch-to-zoom functionality when creating the activity.

fix: App crash while start video content activity in landscape

---

exam/src/main/java/in/testpress/exam/api/ExamService.java
exam/src/main/java/in/testpress/exam/api/TestpressExamApiClient.java
exam/src/main/java/in/testpress/exam/network/NetworkAttemptSection.kt
exam/src/main/java/in/testpress/exam/ui/TestFragment.java

- When concluding the section, we utilize the AttemptSection model for managing network responses from API v2.2.
- However, in commit 0ed10a2, the network response from API v2.2 was modified to API v2.3, preventing us from concluding the section.
- In this particular commit, we substituted AttemptSection with NetworkAttemptSection to effectively handle responses from both API versions 2.2 and 2.3.

fix: Not able end section in resumed exams

---

course/src/main/java/in/testpress/course/ui/CustomTestGenerationActivity.kt

- In this commit, we introduced a distinct JavaScript interface method for initiating the custom test in quiz mode.
- This method is used to start quiz exams from webView.

fix: Add methos to start quiz exam for custom test

---

course/src/main/java/in/testpress/course/network/NetworkContentAttempt.kt
exam/src/main/java/in/testpress/exam/domain/DomainAttempt.kt
exam/src/main/java/in/testpress/exam/domain/DomainAttemptSection.kt
exam/src/main/java/in/testpress/exam/network/NetworkAttempt.kt
exam/src/main/java/in/testpress/exam/network/NetworkAttemptSection.kt

- In ExamContentRepository we are parsing Network response to Domain response this process is not done properly 
- During this conversion, attempts are not being retrieved due to improper parsing.
- In this commit, we have included the necessary files that were missing for proper parsing.

fix: Attempt not receiving in domain model

---

course/src/main/java/in/testpress/course/ui/QuizActivity.kt
course/src/main/res/layout/quiz_container_layout.xml

- Previously we used an "Exit" image within the quiz template to conclude the exam. However, in this latest commit, we have substituted it with a "END" text displayed using a TextView.

fix: Replace ImageView with TextView in quiz template

---

core/src/main/java/in/testpress/models/greendao/Exam.java

- If we passing class object in intent we need to add parcelable for all filed .
- We are not done for this `enableQuizMode` field in exam object.

fix: Add enableQuizMode field as parcelable in exam model

---

core/src/main/java/in/testpress/models/greendao/Exam.java

- If we passing class object in intent we need to add parcelable for all filed .
- We are not done for this `disableAttemptResume` field in exam object.

fix: Add disableAttemptResume field as parcelable in exam model

---

course/src/main/java/in/testpress/course/fragments/BaseExamWidgetFragment.kt

- Replace the names of hasMultipleLanguages with discardExamDetails to make it intentionally revealing.
- Because we actually pass this field to determine whether to show or discard ExamDetails in BaseExamWidgetFragment.

refactor: Rename hasMultipleLanguages with discardExamDetails

---

core/src/main/java/in/testpress/models/greendao/Exam.java
course/src/main/java/in/testpress/course/fragments/BaseExamWidgetFragment.kt
exam/src/main/java/in/testpress/exam/domain/DomainExamContent.kt
exam/src/main/java/in/testpress/exam/ui/TestActivity.java
exam/src/main/java/in/testpress/exam/ui/TestFragment.java
exam/src/main/res/values/strings.xml

- In this commit, we are added to show a warning alert to the user before starting the exam if the attempt resume is disabled

fix: Add show Resume disabled warning before start exam

---

course/src/main/java/in/testpress/course/fragments/BaseExamWidgetFragment.kt
course/src/main/java/in/testpress/course/ui/ContentAttemptListAdapter.java

- Added support to end paused attempt if `disable_attempt_resume` is enabled for the exam.

fix: Add support to end paused attempt

---

exam/src/main/java/in/testpress/exam/ui/TestFragment.java

- In this commit, we added a show exam end alert box when the user tries to close or submit the exam if the `disableAttemptResume` field is true in the exam.

fix: Show Exam end alert when user try to close or submit the exam

---

core/src/main/assets/testpress_questions_typebase.css
course/src/main/java/in/testpress/course/fragments/QuizQuestionFragment.kt

- This commit introduces a 50-50 helpline option to the quiz template. We're incorporating this feature into the Android app to align with its existing availability on the web quiz template.
- When a user clicks the 50-50 button we remove half of the options in the choice list

fix: Add 50-50 helpline option in quiz template

---

course/src/main/java/in/testpress/course/fragments/QuizQuestionFragment.kt
course/src/main/java/in/testpress/course/fragments/QuizSlideFragment.kt
course/src/main/java/in/testpress/course/fragments/RootQuizFragment.kt

- This commit introduces a skip helpline option to the quiz template. We're incorporating this feature into the Android app to align with its existing availability on the web quiz template.
- When a user clicks the skip button we show the solution page for the current question

fix: Add skip helpline option in quiz template

---

core/src/main/assets/TestpressImageTagHandler.js
course/src/main/java/in/testpress/course/fragments/QuizQuestionFragment.kt

- In the context of exam templates, we employ a Webview. We create HTML data and feed it to the Webview. If the Webview includes any image tags, we attach a shared listener to open images in a new window. However, for helpline images within the quiz template, we wish to avoid displaying them in a new window, so we exclude the process of adding the onclick event for these specific images.

fix: Disable onClick event for helpline images in quiz exam

---

course/src/main/java/in/testpress/course/fragments/QuizQuestionFragment.kt

- In the past, we implemented an onClick event for the button located within the helpline container. However, the button was challenging for users to click. As a solution, we are relocating the onClick event to helpline container, which contains both an image and a button, to enhance the user experience.

fix: Add click listener to helpline option container

---

core/src/main/java/in/testpress/models/greendao/Video.java

- We are passing the video model via intent in many places, parcelable is required to pass custom objects via intent.
- In this commit, we are adding missed fields for parcelable in the video model.

 fix: Add missed field for parcelable in video model

---

core/src/main/java/in/testpress/fragments/EmptyViewFragment.kt
core/src/main/res/values/strings.xml

- Previously we used to display permission-denied messages for scheduled content.
- When a user received a notification for scheduled content they couldn't open, we presented a permission-denied message. This message was confusing for users because they would click the notification, only to encounter a permission denied error.
- In this commit, we have improved the user experience by showing the appropriate scheduled message when users attempt to open scheduled content through notifications.

fix: Display the scheduled message content instead of the permission denied message for scheduled content.

---

core/src/main/java/in/testpress/fragments/EmptyViewFragment.kt
core/src/main/res/values/strings.xml
course/src/main/java/in/testpress/course/fragments/ContentLoadingFragment.kt
course/src/main/java/in/testpress/course/fragments/VideoContentFragment.kt

- This problem has been addressed on the web, and we are currently implementing a similar fix in the Android app.
- When a user attempts to access a video content, we first verify whether the course has a video view limit, and if it does, we refresh the content detail view.
- After the content detail view finishes loading, we will use the `isViewsExhausted` field to display an error page indicating that the views limit has been reached.

fix: User able to access embed video content after its views limit exhausted

---

core/src/main/java/in/testpress/util/PermissionHandler.kt
exam/src/main/java/in/testpress/exam/ui/TestQuestionFragment.java

- When a user tries to upload a file in response to a question about file types, we check if the user has given permission for storage access. If permission is granted, we proceed to open the file manager. However, if permission is not granted, we prompt the user to provide the necessary permission.
- If the user has previously denied permission, we cannot request it again. In this commit, we have included the feature to display a message in a snackbar, notifying the user that the required permission is essential if they have previously denied it.

fix: Unable to upload a file in file type questions.

---

core/src/main/java/in/testpress/util/FullScreenChromeClient.java
course/src/main/java/in/testpress/course/fragments/WebViewVideoFragment.kt

- In commit b48068f, we deactivated the long-press option. However, when the user transitions to fullscreen mode, we alter the view so the disabled long-press option is ineffective. In this particular commit, we addressed this issue by disabling the long-press option when switching to fullscreen mode. This is achieved through the use of the disableLongPress variable, which is set to its default value of false.

fix: Prevent users from copying a YouTube video link while in fullscreen.

---

core/src/main/java/in/testpress/models/InstituteSettings.java
course/src/main/java/in/testpress/course/ui/CourseListFragment.java
samples/src/main/java/in/testpress/samples/course/CourseSampleActivity.java

- Added the 'storeEnable' field in institute settings.
- In this commit, we handled adding the product list view in the CourseListFragment based on the 'storeEnable' field in institute settings.

fix: Hide product list fragment if store is disabled in CourseListFragment

---

course/src/main/java/in/testpress/course/ui/viewholders/BaseContentListItemViewHolder.kt

- In this commit, we assign a null value to the thumbnail ImageView if the thumbnail URL is null in the content.

fix: Incorrect thumbnail showing in Content list view

---

course/src/main/java/in/testpress/course/fragments/CourseContentListFragment .kt
course/src/main/java/in/testpress/course/ui/ChapterDetailActivity.java
samples/src/main/java/in/testpress/samples/core/TestpressCoreSampleActivity.java
samples/src/main/java/in/testpress/samples/course/NavigationDrawerActivity.java

- We initially initialized the CourseContentListFragment with constructor parameters in the ChapterDetailActivity. However, during activity and fragment recreation, these constructors would not be called, and only the default constructor would be invoked. This prevented us from properly initializing the CourseContentListFragment, leading to the app crash.
- In this commit, we addressed this issue by passing the type value as an argument and removing the constructor parameters in the CourseContentListFragment.

fix: App crash when the ChapterDetailActivity re-instantiated

---

core/src/main/java/in/testpress/fragments/WebViewFragment.kt
core/src/main/java/in/testpress/ui/AbstractWebViewActivity.kt
core/src/main/java/in/testpress/util/webview/CustomWebViewClient.kt
course/src/main/java/in/testpress/course/fragments/LiveStreamFragment.kt
course/src/main/java/in/testpress/course/ui/CourseListFragment.java

- We initially initialized the WebViewFragment with constructor parameters. However, during activity and fragment recreation, these constructors would not be called, and only the default constructor would be invoked. This prevented us from properly initializing the WebViewFragment, leading to the app crash.
- In this commit, we addressed this issue by passing all values as an argument and removing the constructor parameters in the WebViewFragment.

fix: App crash when the WebViewFragment re-instantiated

---

core/src/main/java/in/testpress/fragments/WebViewFragment.kt
core/src/main/java/in/testpress/util/webview/CustomWebViewClient.kt

- Previously, we fetched instituteSettings during fragment creation, making it impossible to use the WebView fragment when the user is not authenticated.
- In this commit, we fetch instituteSettings if SSO is required; otherwise, instituteSettings will be null.

refactor: Fetch the instituteSettings only for SSO login

---

course/src/main/java/in/testpress/course/ui/CustomTestGenerationActivity.kt
exam/src/main/java/in/testpress/exam/ui/TestFragment.java

- Initially, The exam timer is not available for custom tests because it has infinite time.
- In this commit, we have introduced an exam time limit for custom tests. If the user selects a specific time, the exam timer will be displayed; otherwise, it remains hidden.

fix: Add exam timer for custom test

---

exam/src/main/java/in/testpress/exam/ui/TestFragment.java

- In this bcc2c5c we added support to show a timer for custom tests we are accessing the exam in timer click listener
- While clicking the timer view it accesses the exam object but the exam object is null for the custom test.
- In this commit, we handled to show pause exam alert dialog or end exam alter dialog according to the exam object.

fix: App crash when user clicks the timer view

---

exam/src/main/java/in/testpress/exam/ui/ReviewQuestionsFragment.java
exam/src/main/java/in/testpress/exam/ui/viewmodel/ReportQuestionViewModel.kt

- In commit 489ee14, we removed the functionality to report questions for the custom test solution. This change was necessary because it required an examId that we don't have for custom tests.
- Recently, we added support for reporting questions on the web, and now we can report questions without needing an examId. As a result, in this commit and onwards, we permanently display the 'Report Question' button on the solution page for both normal exams and custom tests.
- We do not include the `examId` as param when reporting a question for a custom test.

enhancement: Add a question report button on the custom test solution page

---

core/src/main/java/in/testpress/util/TimeUtils.kt
exam/src/main/java/in/testpress/exam/ui/ReviewStatsFragment.java

- In this commit bcc2c5c, a timer for a custom test has been added. When the user finishes the exam, the report page is displayed without showing the total time.
- In this commit, we showcase the total time on the report page by adding both the `timeTaken` and `remainingTime` values in attempt.

fix: Show total time in TestReport page

---

core/src/main/java/in/testpress/util/extension/Activity.kt
course/src/main/java/in/testpress/course/ui/CustomTestGenerationActivity.kt
course/src/main/res/values/strings.xml
exam/src/main/java/in/testpress/exam/api/ExamService.java
exam/src/main/java/in/testpress/exam/api/TestpressExamApiClient.java

- In this commit, we introduced a JavaScript interface method `showReview()` in CustomTestGenerationActivity to display the review page on Android. Now, when users click on a review, we fetch the corresponding attempt using the `attemptId` and open the review page.

enhancement: Add support to open review page from custom test webview

---

course/src/main/java/in/testpress/course/ui/CustomTestGenerationActivity.kt

- Previously when pressing the back button we navigated between the webview if it have a back stack.
- In this commit, the activity is closed when the user presses the back button.

fix: Close Custom test activity when user press the back button

---

course/src/main/java/in/testpress/course/ui/CustomTestGenerationActivity.kt

- Previously, when the user opened the review activity from the custom test, we would finish the custom test activity.
- With this commit, we no longer finish the custom test activity.

fix: Prevent Custom test activity closing

---

course/src/main/java/in/testpress/course/fragments/DocumentViewerFragment.kt

- Activity recreation occurs when the device experiences low memory. This issue specifically occurs in the `DocumentViewerFragment`, where we access the `pdfDownloadManager` within the `onDetach()` lifecycle event. The `pdfDownloadManager` is declared as a `lateinit` property, and during the `onDetach()` call, the application crashes due to the `pdfDownloadManager` not being initialized at that point.
- In this commit, we handled the Initialization check in `onDetach()` function.

fix: App crash when the DocumentViewerFragment re-instantiated

---

course/src/main/java/in/testpress/course/util/ZoomMeetHandler.kt

- In commit e826f09, we hide the Zoom meeting URL to prevent users from sharing the meeting link.
- However, we encountered an issue in the `onZoomSDKInitializeResult()` method, which is triggered upon successful or failed initialization of the Zoom SDK. In the case of failure, `ZoomSDK.zoomUIService` becomes null at the time we try to hide the meeting URL leading to the application crash.
- To address this issue, we have now implemented a solution to hide the meeting URL when the user starts the meeting.

 fix:  App crash on Video Conference detail page upon network reconnection

---

core/src/main/java/in/testpress/fragments/WebViewFragment.kt
core/src/main/java/in/testpress/util/WebViewUtils.java

- The cache mode for the WebView in the WebViewUtils class has been switched from LOAD_NO_CACHE to LOAD_CACHE_ELSE_NETWORK. This adjustment aims to enhance performance by leveraging cached resources whenever possible, resorting to network resources only when necessary.
- By making these adjustments, WebView is now designed to prioritize loading resources from the cache when available, thereby minimizing unnecessary downloads and preserving user data.

fix: Change WebView cache mode to `LOAD_CACHE_ELSE_NETWORK`

---

core/src/main/java/in/testpress/util/Misc.kt
exam/src/main/java/in/testpress/exam/ui/TestQuestionFragment.java

- Previously, we used to verify file access permissions before uploading files from Android. Starting from Android 13, permission is no longer required to access the file picker. Now, permission checks are only conducted for Android 12 and below.

fix: Not able to upload file in file type question

---

course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java

- Previously, device orientation was locked to portrait mode upon entering video content.
- Android 12 and higher versions enforce orientation lock on large-screen devices, preventing orientation switching.
- This commit replaces the portrait orientation lock with fullscreen mode activation when the device is in landscape orientation.

fix: Unable to enter fullscreen mode while watching the video.

---

course/src/main/java/in/testpress/course/util/ZoomMeetHandler.kt
course/src/main/res/values/config.xml

- In commit e47a34c, the Zoom SDK was updated, and at that time, the functionality to restrict users from taking screen captures was deprecated.
- In this commit, we fixed the issue by adding `zoomSDK.zoomUIService?.setNewMeetingUI(ZoomMeetActivity::class.java)`, allowing us to restrict users from taking screen captures.
- Additionally, we removed `config.xml` because it is no longer required since we are achieving the functionality through the aforementioned method.

fix: Prevent screen captures during Zoom classes. 

---

course/build.gradle

- Changed dependencies to API for the following packages in this commit
- `android-pdf-viewer`, `PRDownloader`, `DoubleTapPlayerView`
- By doing this, we don't need to implement the following dependencies in the app project.

enhancement: Use dependency as API instead of implementation

---

build.gradle
core/build.gradle
course/src/main/java/in/testpress/course/fragments/BaseContentDetailFragment.kt
course/src/main/java/in/testpress/course/fragments/BaseExamWidgetFragment.kt
course/src/main/java/in/testpress/course/fragments/ContentBottomNavigationFragment.kt
course/src/main/java/in/testpress/course/fragments/ContentLoadingFragment.kt
course/src/main/java/in/testpress/course/fragments/DownloadsFragment.kt
course/src/main/java/in/testpress/course/fragments/LoadingQuestionsFragment.kt
course/src/main/java/in/testpress/course/fragments/NativeVideoWidgetFragment.kt
course/src/main/java/in/testpress/course/fragments/QuizAttemptsList.kt
course/src/main/java/in/testpress/course/fragments/QuizQuestionFragment.kt
course/src/main/java/in/testpress/course/fragments/QuizReviewFragment.kt
course/src/main/java/in/testpress/course/fragments/StartQuizFragment.kt
course/src/main/java/in/testpress/course/fragments/WebViewVideoFragment.kt
course/src/main/java/in/testpress/course/ui/ContentListFragment.kt
course/src/main/java/in/testpress/course/ui/QuizActivity.kt
course/src/main/java/in/testpress/course/util/ZoomMeetHandler.kt
exam/build.gradle

- Updated Kotlin version from `1.6.0` to `1.7.0` and corresponding room database version from `2.4.0` to `2.4.3`.
- Added an `else` branch for all when statements due to Kotlin `1.7.0` changes, where `when` statements with `enum`, `sealed`, and `Boolean` subjects are exhaustive by default. More details can be found in the [[Docs](https://kotlinlang.org/docs/compatibility-guide-17.html#make-when-statements-with-enum-sealed-and-boolean-subjects-exhaustive-by-default)] and [[Issue](https://youtrack.jetbrains.com/issue/KT-47709?_gl=1*fa3yyi*_ga*MTE2NDk5ODIwNC4xNzEzNDM5NDk1*_ga_9J976DJZ68*MTcxMzQzOTQ5NC4xLjEuMTcxMzQ0MDU1Ni42MC4wLjA.&_ga=2.73157715.1326330261.1713439495-1164998204.1713439495)].

enhancement: Update Kotlin version to 1.7.0

---

build.gradle
course/src/androidTest/AndroidManifest.xml
gradle/wrapper/gradle-wrapper.properties

- Updated Android Gradle Plugin version from `7.0.4` to `7.2.2`.
- Updated Gradle version from `7.3.2` to `7.3.3`.
- Updated SDK Build Tools from `30.0.2` to `30.0.3`.
- Updated corresponding dependencies. See [Docs](https://developer.android.com/build/releases/past-releases/agp-7-2-0-release-notes) for more details.

enhancement: Update Android Gradle Plugin version to `7.2.2`

---

course/src/main/java/in/testpress/course/ui/ChaptersListFragment.java

- Added a custom test icon to the ChaptersListFragment in commit 87c8943. We use the `allowCustomTestGeneration` field to handle this icon, which is present in the course object.
- If the user opens the chapter list fragment via deep link and the `allowCustomTestGeneration` field and course object are null, the app crashes.
- In this commit, we validate the custom test icon after the course is fetched to prevent the crash.

fix: App crash while opening chapters list fragment via deep link

---

core/build.gradle
core/src/main/AndroidManifest.xml
core/src/main/java/in/testpress/core/TestpressSdk.java
core/src/main/java/in/testpress/models/InstituteSettings.java
samples/src/main/java/in/testpress/samples/core/TestpressCoreSampleActivity.java
samples/src/main/java/in/testpress/samples/course/CourseSampleActivity.java
samples/src/main/java/in/testpress/samples/course/NavigationDrawerActivity.java
samples/src/main/java/in/testpress/samples/exam/ExamSampleActivity.java
samples/src/main/java/in/testpress/samples/exam/NavigationDrawerActivity.java

- In this commit, we added Sentry support to receive all crash reports occurring in the Testpress SDK.

enhancement: Add sentry support

---

course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java
course/src/main/res/values/strings.xml

- Previously, we only handled errors for network errors, leaving other errors to display an empty screen, making it difficult to identify the actual error.
- In this commit, we have added specific error messages for each error, making it easier to identify and understand the errors.

fix: Handled Error message in exoplayer

---

course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java
course/src/main/java/in/testpress/course/util/VideoUtils.kt
course/src/main/res/values/strings.xml

- In this commit, we added a randomly generated string known as `playback_id` to the error message, displaying it as error text. Furthermore, we included the Sentry logger to handle this, ensuring the `playback_id` tag is utilized for improved error tracking.

enhancement: Add Sentry Message Capture with `playback_id` for Exo player errors

---

store/src/main/java/in/testpress/store/ui/OrderConfirmActivity.java

- In this commit, we modified the access modifier in `OrderConfirmActivity` to enable users to display their custom pages for success and failed responses.
- Additionally, we extracted the purchase logging and loading view in `OrderConfirmActivity`.

fix: Modified access modifier in `OrderConfirmActivity`.

---

core/src/main/java/in/testpress/fragments/WebViewFragment.kt

- Previously, we were clearing all cookies while loading the WebView, which also cleared any custom headers added to the WebView.
- By removing the process of clearing all cookies, this issue will be fixed.
- The cookie clearing process was initially added to fix an issue in commit b04ebc4.
- Now, this process is no longer required because the issue is already handled on the web.

fix: Custom header getting removed in WebView

---

store/src/main/java/in/testpress/store/models/OrderItem.java
store/src/main/java/in/testpress/store/models/PriceItem.kt
store/src/main/java/in/testpress/store/models/Product.java
store/src/main/java/in/testpress/store/models/ProductDetailResponse.kt
store/src/main/java/in/testpress/store/network/ProductService.java
store/src/main/java/in/testpress/store/network/StoreApiClient.java
store/src/main/java/in/testpress/store/ui/OrderConfirmActivity.java
store/src/main/java/in/testpress/store/ui/ProductDetailsActivity.java

- Upgraded the order API from version `v2.2` to version `v3`.
- Added required parameters `price_id` and `product_slug` to the `order_item` in the order API request body.
- Added an option to retrieve `price_id` via intent; if the intent value is not available, the first index value in the price list will be used by default.
- Although there is currently no UI for selecting from multiple prices, this commit includes SDK changes that enable the Yukthi app to use this feature immediately.

enhancement: Add option to purchase product at multiple prices

---

store/src/main/java/in/testpress/store/models/OrderItem.java
store/src/main/java/in/testpress/store/ui/OrderConfirmActivity.java

- In commit 85b5204, the data type of the price field was changed to Integer.
- While creating an order, the price_id value (an Integer) was posted in the price field, hence the change.
- However, after the order is created, the response includes the price as a string with the actual product price.
- This discrepancy prevents product purchases.
- Changing the data type back to String resolves this issue, as the backend can automatically convert the string to an integer when necessary.

fix: Change data type of price field to String in `OrderItem` model

---

exam/src/main/java/in/testpress/exam/ui/ReviewStatsFragment.java

- Previously, the Analytics button was shown even when Analytics was disabled in the exam settings.
- In this commit, the Analytics button is now hidden if Analytics is disabled in the exam settings.

fix: Hide Analytics button when Analytics is disabled in Exam

---

exam/src/main/res/values/strings.xml

- In commit 44ed6a7, we fixed the preemptive section ending but did not update the section lock message in the alert dialog.
- In this commit, the section lock message in the alert dialog has been updated.

fix: Update Section Lock Message in Alert Dialog

---

core/src/main/java/in/testpress/util/webview/CustomWebViewClient.kt

- Fix issue where hyperlinks containing PDF files are not responsive in Android WebView due to lack of native PDF support.
- In this commit, we check if the request URL points to a PDF. If it does, we open the PDF in an external browser instead.
- This ensures that PDF links are handled appropriately, providing a better user experience.

fix: Handle PDF Hyperlinks in WebView by Opening in Browser

---

core/src/main/java/in/testpress/database/Room.kt
core/src/main/java/in/testpress/database/dao/OfflineExamDao.kt
course/src/main/java/in/testpress/course/network/CourseService.kt
course/src/main/java/in/testpress/course/network/NetworkContent.kt
course/src/main/java/in/testpress/course/repository/OfflineExamRepository.kt
course/src/main/java/in/testpress/course/viewmodels/OfflineExamViewModel.kt
samples/build.gradle
samples/src/main/AndroidManifest.xml
samples/src/main/java/in/testpress/samples/course/CourseSampleActivity.java
samples/src/main/java/in/testpress/samples/course/OfflineExamSampleActivity.kt
samples/src/main/res/layout/activity_offline_exam_sample.xml
samples/src/main/res/layout/activity_open_in.xml

- Implemented the repository pattern to download exams and exam settings and store them in the local database.
- Added a sample activity in the sample app to test the download functionality for exams.

feat: Add option to download Exam

---

core/schemas/in.testpress.database.TestpressDatabase/21.json
core/src/main/java/in/testpress/database/Room.kt
core/src/main/java/in/testpress/database/dao/LanguageDao.kt
core/src/main/java/in/testpress/database/entities/Language.kt
core/src/main/java/in/testpress/database/roommigration/RoomMigration20To21.kt
core/src/main/java/in/testpress/util/extension/Long.kt
core/src/main/java/in/testpress/util/extension/String.kt
course/src/main/java/in/testpress/course/network/CourseService.kt
course/src/main/java/in/testpress/course/repository/OfflineExamRepository.kt
exam/src/main/java/in/testpress/exam/network/NetworkLanguage.kt

- Implemented the repository pattern to download languages for downloaded exam and store them in the local database.
- Added a sample activity in the sample app to test the download functionality for exams.

feat: Add option to download Languages

---

core/schemas/in.testpress.database.TestpressDatabase/22.json
core/src/main/java/in/testpress/database/Room.kt
core/src/main/java/in/testpress/database/dao/DirectionDao.kt
core/src/main/java/in/testpress/database/dao/ExamQuestionDao.kt
core/src/main/java/in/testpress/database/dao/QuestionDao.kt
core/src/main/java/in/testpress/database/dao/SectionsDao.kt
core/src/main/java/in/testpress/database/dao/SubjectDao.kt
core/src/main/java/in/testpress/database/entities/Answer.kt
core/src/main/java/in/testpress/database/entities/ExamQuestion.kt
core/src/main/java/in/testpress/database/entities/Question.kt
core/src/main/java/in/testpress/database/roommigration/RoomMigration21To22.kt
core/src/main/java/in/testpress/util/Converters.kt
course/src/main/java/in/testpress/course/network/CourseService.kt
course/src/main/java/in/testpress/course/network/NetworkOfflineQuestionResponse.kt
course/src/main/java/in/testpress/course/repository/OfflineExamRepository.kt

- Implemented the repository pattern to download Questions, Sections, Subjects, Directions, ExamQuestions, and Answers for downloaded exam and store them in the local database.
- Added a sample activity in the sample app to test the download functionality for exams.

 feat: Add option to download Questions

---

core/src/main/java/in/testpress/v2_4/models/ApiResponse.java
exam/src/main/java/in/testpress/exam/api/ExamService.java
exam/src/main/java/in/testpress/exam/api/TestpressExamApiClient.java
exam/src/main/java/in/testpress/exam/ui/AttemptsActivity.java
exam/src/main/java/in/testpress/exam/ui/ReviewQuestionsActivity.java
exam/src/main/java/in/testpress/exam/ui/TestActivity.java

- Replaced `TestpressApiResponse<Language>` with `ApiResponse<List<Language>>` in the `getLanguages` method.
- The `ApiResponse` class is now used for all paginated API calls due to its support for both flat nested objects and list responses, unlike the previous implementation which lacked support for flat nested objects.

Refactor: Use ApiResponse class to parse languages

---

exam/src/main/java/in/testpress/exam/models/AttemptAnswer.java
exam/src/main/java/in/testpress/exam/models/AttemptItem.java
exam/src/main/java/in/testpress/exam/models/AttemptQuestion.java
exam/src/main/java/in/testpress/exam/models/Permission.java

- Added constructors to the following models: `AttemptAnswer`, `AttemptItem`, `AttemptQuestion`, `Permission`. These constructors enable the local initialization of objects, which is crucial for offline exam support. Previously, these fields were only used for API responses and implemented with Parcelable.

feat: Add Constructors to Models for Offline Exam Support

---

core/src/main/java/in/testpress/database/entities/OfflineAttempt.kt
core/src/main/java/in/testpress/database/entities/OfflineAttemptSection.kt
core/src/main/java/in/testpress/database/entities/OfflineCourseAttempt.kt

- Previously, we mistakenly set the default value to 1, causing the deletion of old attempts whenever a new attempt was created.
- When setting a primary key to auto-generate, the default value should be set to 0 for it to work correctly.

fix: Prevent Deletion of Existing Attempts

---

exam/src/main/java/in/testpress/exam/repository/AttemptRepository.kt
exam/src/main/java/in/testpress/exam/ui/TestFragment.java
exam/src/main/java/in/testpress/exam/ui/viewmodel/AttemptViewModel.kt

- Implemented the Repository pattern to the start and end sections of the exam.
- Previously, this functionality was handled directly within the `TestFragment`.

enhancement: Add method to update section via repository

---

core/src/main/java/in/testpress/database/dao/DirectionDao.kt
core/src/main/java/in/testpress/database/dao/ExamQuestionDao.kt
core/src/main/java/in/testpress/database/dao/OfflineAttemptDao.kt
core/src/main/java/in/testpress/database/dao/OfflineAttemptItemDao.kt
core/src/main/java/in/testpress/database/dao/OfflineAttemptSectionDao.kt
core/src/main/java/in/testpress/database/dao/OfflineCourseAttemptDao.kt
core/src/main/java/in/testpress/database/dao/QuestionDao.kt
core/src/main/java/in/testpress/database/dao/SubjectDao.kt
core/src/main/java/in/testpress/database/mapping/OfflineAttemptMapping.kt
core/src/main/java/in/testpress/database/mapping/OfflineAttemptSectionMapping.kt
core/src/main/java/in/testpress/util/Converters.kt
exam/src/main/java/in/testpress/exam/repository/AttemptRepository.kt
exam/src/main/java/in/testpress/exam/ui/TestActivity.java
exam/src/main/java/in/testpress/exam/ui/TestFragment.java
exam/src/main/java/in/testpress/exam/ui/viewmodel/AttemptViewModel.kt
exam/src/main/java/in/testpress/exam/util/OfflineAttemptItemMapping.kt

- Added creation of OfflineAttemptItem using exam questions, currently for exams without sections.
- Enabled users to take exams offline by creating attempts and updating answers locally.
- Set the status of the attempt to 'complete' when the user ends the exam.

feat: Create attempt item offline and integrate with existing exam template

---

core/src/main/java/in/testpress/database/mapping/OfflineAttemptSectionMapping.kt
core/src/main/java/in/testpress/models/greendao/AttemptSection.java

- We are passing the `AttemptSection` model via intent in many places, parcelable is required to pass custom objects via intent.
- In this commit, we are adding missed fields for parcelable in the `AttemptSection` model.

 fix: Add missed field for parcelable in `AttemptSection` model

---

core/src/main/java/in/testpress/database/dao/OfflineAttemptDao.kt
exam/src/main/java/in/testpress/exam/repository/AttemptRepository.kt
exam/src/main/java/in/testpress/exam/ui/TestFragment.java
exam/src/main/java/in/testpress/exam/ui/viewmodel/AttemptViewModel.kt

- For offline exams, we need to handle the remaining time and last started time for attempts. In this commit, we are updating the `remainingTime` and `lastStartedDate` whenever the user saves their answers.

fix: Update Remaining Time and Last Started Time While Updating Answer Locally

---

course/src/main/java/in/testpress/course/fragments/BaseExamWidgetFragment.kt
course/src/main/java/in/testpress/course/fragments/ContentLoadingFragment.kt

- Previously, the content was refreshed in `ContentLoadingFragment`, which showed an internet error if the internet was not connected.
- In this commit, the exam detail view is shown even if the internet is not available. Therefore, the content is now refreshed in `BaseExamWidgetFragment` instead of `ContentLoadingFragment`.

fix: Refresh Exam Content in BaseExamWidgetFragment

---

course/src/main/java/in/testpress/course/fragments/BaseExamWidgetFragment.kt
exam/src/main/java/in/testpress/exam/domain/DomainExamContent.kt

- Previously, CTET Exam templates were not supported on Android.
- In this commit, we added support to open CTET Exams in a WebView.

fix: Open CTET Exam in WebView

---

core/src/main/java/in/testpress/database/dao/OfflineAttemptDao.kt
core/src/main/java/in/testpress/database/dao/OfflineAttemptItemDao.kt
core/src/main/java/in/testpress/database/dao/OfflineCourseAttemptDao.kt
core/src/main/java/in/testpress/database/dao/OfflineExamDao.kt
course/src/main/java/in/testpress/course/fragments/BaseExamWidgetFragment.kt
course/src/main/java/in/testpress/course/repository/OfflineExamRepository.kt
course/src/main/java/in/testpress/course/viewmodels/OfflineExamViewModel.kt
course/src/main/res/layout/attempts_list_view.xml
course/src/main/res/layout/exam_start_screen.xml
course/src/main/res/layout/quiz_start_screen.xml
exam/src/main/java/in/testpress/exam/repository/AttemptRepository.kt
exam/src/main/java/in/testpress/exam/repository/ExamRepository.kt
exam/src/main/java/in/testpress/exam/ui/TestActivity.java
exam/src/main/java/in/testpress/exam/ui/TestFragment.java

- Added a Resume Offline Exam button that allows users to resume paused offline attempts.
- Users must complete the resumed attempt before starting a new attempt for the same exam.

feat: Add resume offline button in exam detail screen

---

course/src/main/java/in/testpress/course/fragments/AttemptsListFragment.kt
course/src/main/java/in/testpress/course/fragments/BaseExamWidgetFragment.kt
course/src/main/java/in/testpress/course/fragments/ExamStartScreenFragment.kt

- Previously, the view was displayed before the language was fully fetched. In this commit, we ensured the view is displayed only after the language fetch is complete.

fix: Show Exam start button and Download Button in same time

---

course/src/main/java/in/testpress/course/fragments/BaseExamWidgetFragment.kt
course/src/main/res/values/strings.xml
exam/src/main/res/values/strings.xml

- Updated the names of the exam start buttons for better clarity.
- Changed the existing button name to `Start Exam Online`.
- Added a new button named `Start Exam Offline` to support the offline exam functionality recently added to the exam detail view.

refactor: Exam Start Button Naming

---

exam/src/main/java/in/testpress/exam/repository/ExamRepository.kt
exam/src/main/java/in/testpress/exam/ui/TestActivity.java
exam/src/main/java/in/testpress/exam/ui/viewmodel/ExamViewModel.kt

- Added option to handle ending offline exams from the exam start screen.
- Previously, the internet was required to perform this action.

fix: Not able to end Offline Exam from TestActivity

---

exam/src/main/java/in/testpress/exam/ui/TestFragment.java

- In this commit 44ed6a7, we added validation for Preemptive Section Ending while ending the exam.
- However, Preemptive Section Ending only works when all sections have a time limit, causing issues with ending exams for sections without a time limit.
- Therefore, we check if the exam has a section lock before showing the exam end dialog box.

fix: Not able to end Exam if the section time is not given

---

exam/src/main/java/in/testpress/exam/ui/TestFragment.java

- Previously, while saving answers, we were updating the questionList, which was unnecessary.
- Additionally, we were updating the questionList after fetching all user-selected answers, which was also unnecessary.
- Due to these updates, lagging occurred while switching questions.
- In this commit, we have removed the unnecessary questionList updating part to resolve the lagging issue.

 fix: Lagging between switching questions on the offline exam

---

core/src/main/java/in/testpress/database/dao/OfflineAttemptDao.kt
course/src/main/java/in/testpress/course/repository/OfflineExamRepository.kt

- Previously, when deleting an offline exam, only the exam itself was deleted.
- In this commit, we added the option to delete all running and completed attempts related to the exam.

fix: Delete Offline Attempts when deleting the exam

---

course/src/main/java/in/testpress/course/fragments/LiveStreamFragment.kt

In this commit, we validate the live stream URL. If the URL is null or empty, we show the live Not Started notice message.

fix: Show Live Not Started Notice Message

---

course/src/main/java/in/testpress/course/fragments/BaseExamWidgetFragment.kt

- When reloading the content, the download button was showing before the Start Exam Online button.
- In this commit, we ensured that both buttons appear in the UI at the same time.

fix: Download Exam button showing before Start Exam Online button

---

core/schemas/in.testpress.database.TestpressDatabase/27.json
core/src/main/java/in/testpress/database/Room.kt
core/src/main/java/in/testpress/database/dao/OfflineExamDao.kt
core/src/main/java/in/testpress/database/entities/OfflineExam.kt
core/src/main/java/in/testpress/database/roommigration/RoomMigration26To27.kt
course/src/main/java/in/testpress/course/fragments/BaseExamWidgetFragment.kt
course/src/main/java/in/testpress/course/repository/OfflineExamRepository.kt

- In this commit, we are adding the `downloadComplete` field to handle the download exam button.
- This field's default value is false. Once the exam download is complete, we update it to true.

feat: Add `downloadComplete` Field in OfflineExam Model

---

core/src/main/java/in/testpress/util/NetworkUtil.kt
course/src/main/java/in/testpress/course/fragments/LiveStreamFragment.kt
course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java
course/src/main/res/layout/exo_player_view.xml

- Previously, we were showing the livestream not started notice message on the full screen. Now, the notice message will be shown on the player view.
- During this process, we reload the content details every 15 seconds until we get the livestream URL.
- Once we get the livestream URL, we load the player and check for errors. If an error occurs, we show the livestream not started notice message again and make API requests for the URL every 5 seconds until we receive a successful response.
- Once we get a successful response, we load the player again and the livestream will begin.

fix: Show Livestream Notice Message on the Player View

---

course/src/main/java/in/testpress/course/fragments/BaseExamWidgetFragment.kt
course/src/main/java/in/testpress/course/repository/OfflineExamRepository.kt
course/src/main/java/in/testpress/course/ui/OfflineExamListActivity.kt
course/src/main/java/in/testpress/course/viewmodels/OfflineExamViewModel.kt
exam/src/main/java/in/testpress/exam/ui/TestFragment.java
samples/src/main/java/in/testpress/samples/core/TestpressCoreSampleActivity.java
samples/src/main/java/in/testpress/samples/course/OfflineExamSampleActivity.kt

- Previously, we updated answers whenever the user visited the OfflineExamListActivity.
- In this commit, we've added the option to update answers after the user completes the offline exam. Once the answers are submitted, we show a success message; otherwise, we display an internet error message.

fix: Update Answers After Completing the Offline Exam

---

core/src/main/java/in/testpress/database/dao/OfflineAttemptDao.kt
course/src/main/java/in/testpress/course/repository/OfflineExamRepository.kt
course/src/main/java/in/testpress/course/ui/OfflineExamListActivity.kt
course/src/main/java/in/testpress/course/viewmodels/OfflineExamViewModel.kt
course/src/main/res/layout/sync_action_view.xml
course/src/main/res/menu/offline_attempt_sync.xml

- In this commit, we added a sync button to the action bar. If the offline attempt is not synced, this button will be visible. When the user clicks the button, it will update the offline attempts. Additionally, an animation has been added for the sync button.

fix: Add sync button to update answers

---

core/src/main/java/in/testpress/util/WebViewUtils.java
exam/src/main/java/in/testpress/exam/ui/TestQuestionFragment.java

- For offline exams, we are using WebView. Since there is no internet connection, we are unable to load the WebView and it returns a network error.
- In this commit, we check for WebView errors and if the exam is offline, we ignore the error and show the selected options.

fix: Not Able to Update WebView Without Internet

---

course/src/main/java/in/testpress/course/fragments/BaseExamWidgetFragment.kt

- In this commit, we handle the visibility of the Download Exam button and Start Exam Offline button in the content detail screen based on the isEnded() function. If the exam has ended, we hide all buttons. If the exam has not ended, we show either the Start Exam Offline button (if the exam is already downloaded) or the Download Exam button.

fix: Hide Download and Start Exam Offline buttons if exam has ended

---

exam/src/main/java/in/testpress/exam/repository/ExamRepository.kt

- Previously, we calculated the exam duration based on the exam end date, which caused exceptions if the end date was null.
- We now check if the exam end date is null and, return the exam duration.

fix: Not able to take offline Exam if Exam end date is null

---

core/src/main/java/in/testpress/database/dao/OfflineExamDao.kt
core/src/main/java/in/testpress/database/entities/OfflineExam.kt
course/src/main/java/in/testpress/course/fragments/BaseExamWidgetFragment.kt
course/src/main/java/in/testpress/course/ui/OfflineExamListActivity.kt
exam/src/main/java/in/testpress/exam/repository/AttemptRepository.kt

- Previously, we didn't handle the retake option for offline exams correctly, allowing users to retake the exam multiple times even if retakes were disabled. In this commit, we track the attempt count locally each time a user completes an attempt. Based on this count, we now enforce the retake restrictions as per the exam settings. Additionally, we sync the offline attempts after the exam is completed.

fix: User able to retake offline exam even if retake is disabled

---

course/src/main/java/in/testpress/course/fragments/OfflineExamOptionsBottomSheet.kt
course/src/main/java/in/testpress/course/ui/OfflineExamListActivity.kt
course/src/main/res/drawable/bottom_sheet_background.xml
course/src/main/res/drawable/ic_baseline_delete_forever_24.xml
course/src/main/res/drawable/ic_baseline_more_vert_24.xml
course/src/main/res/drawable/ic_baseline_open_in_new_24.xml
course/src/main/res/layout/offline_exam_list_item.xml
course/src/main/res/layout/offline_exam_options_bottom_sheet.xml
course/src/main/res/values/style.xml

- In this commit, we added an option to open exam details from the Offline Exam List. When the user clicks the More button in the list item, a bottom sheet will open with options to open the exam and delete the exam.

fix: Add option to open exam detail from Offline Exam List view

---

core/src/main/java/in/testpress/models/DiscussionRepository.kt

- `Transformations.map` is deprecated. In this commit, we replaced it with the LiveData `map` function.

refactor: Remove `Transformations.map` from DiscussionRepository

---

core/src/main/java/in/testpress/models/InstituteSettings.java
course/src/main/java/in/testpress/course/ui/ChaptersListFragment.java
course/src/main/java/in/testpress/course/ui/MyCoursesFragment.java
gradle.properties
samples/src/main/java/in/testpress/samples/course/CourseSampleActivity.java

- In this commit, we added a new method called `getDomainUrl()` in the InstituteSettings model.
- This method returns the whiteLabeledHostUrl if it is not null; otherwise, it returns the base URL.

enhancement: Add domain URL method in InstituteSettings

---

exam/src/main/java/in/testpress/exam/repository/AttemptRepository.kt
exam/src/main/java/in/testpress/exam/ui/TestFragment.java
exam/src/main/java/in/testpress/exam/ui/viewmodel/AttemptViewModel.kt

- Previously, we added a new feature called Offline Exam, which relies on the Exam object. However, for custom tests, the Exam object is not required.
- Both features use the same exam template, and in some places, the Exam object was made non-nullable, causing issues with custom tests.
- In this commit, we made the Exam object nullable in all relevant places, resolving the issue.

fix: Unable to take custom test

---

core/src/main/java/in/testpress/database/dao/OfflineExamDao.kt
core/src/main/java/in/testpress/database/entities/OfflineExam.kt
course/src/main/java/in/testpress/course/fragments/BaseExamWidgetFragment.kt
course/src/main/java/in/testpress/course/repository/OfflineExamRepository.kt
course/src/main/java/in/testpress/course/ui/OfflineExamListActivity.kt
course/src/main/java/in/testpress/course/viewmodels/OfflineExamViewModel.kt
exam/src/main/java/in/testpress/exam/repository/AttemptRepository.kt

- Previously, users could attend exams in either offline or online mode even if Retake was disabled. The exam attempt count was not synced correctly, allowing users to take the exam offline after attempting it online.
- In this commit, we added attempt syncing in the Exam detail screen. Whenever the user opens the exam detail screen, the attempt count is synced with the downloaded offline exam. This ensures the attempt count is consistent across both online and offline modes.

fix: Prevent user from taking attempts in exam when Retake is disabled

---

exam/src/main/java/in/testpress/exam/repository/AttemptRepository.kt
exam/src/main/java/in/testpress/exam/util/OfflineAttemptItemMapping.kt

- In this commit, we ensure that local answers are set to the current answers for numerical and essay type questions. These answers will be submitted during the attempt syncing process.

fix: Answers not submitting for numerical and essay type questions

---

core/src/main/java/in/testpress/database/entities/OfflineAttempt.kt
course/src/main/java/in/testpress/course/fragments/BaseExamWidgetFragment.kt
course/src/main/java/in/testpress/course/repository/OfflineExamRepository.kt

- In this commit, we added validation to complete paused attempts for ended exams. This operation is performed before the attempt sync starts, ensuring that all completed exams are properly synced.

fix: Paused attempts not submitted after exam ended

---

exam/src/main/java/in/testpress/exam/repository/AttemptRepository.kt

- When the user ends the exam, we update the offline exam attempt count to sync the attempt count.
- For custom tests, the same process occurs, but the exam object is null. Without the exam object, we can't update the offline exam attempt count, leading to a crash.
- In this commit, we ensure the offline attempt count is updated only if the exam is downloaded offline.

fix: App crash on Custom Test End

---

exam/src/main/java/in/testpress/exam/ui/TestFragment.java

- In commit 1d43aa6, we added a Repository pattern to end the attempt. After ending the attempt, the response value was not being updated, which caused the test results to show zero.
- This commit ensures the response value is updated correctly to display the test results.

fix: Test Report details are showing zero

---

course/src/main/java/in/testpress/course/fragments/AttemptsListFragment.kt
course/src/main/java/in/testpress/course/fragments/BaseExamWidgetFragment.kt
course/src/main/java/in/testpress/course/fragments/ExamStartScreenFragment.kt
course/src/main/java/in/testpress/course/repository/OfflineExamRepository.kt
course/src/main/res/layout/attempts_list_view.xml
course/src/main/res/layout/exam_start_screen.xml
course/src/main/res/layout/quiz_start_screen.xml
course/src/main/res/values/strings.xml

- Previously, after a user completed an offline exam, we navigated them to the exam detail screen, synced the attempt, and displayed a success toast. However, the Exam Start button remained visible, allowing users to attempt the exam offline again.
- In this commit, we removed the success toast, added a message, and hid the buttons once the exam is completed. If there is no network to sync the attempt, we display a network error message instead.

fix: User can take the exam even if retake is disabled

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

- Updated Android Gradle Plugin version from `7.2.2` to `7.4.2`.
- Updated Gradle version from `7.3.3` to `7.5`.
- Updated corresponding dependencies. See [Docs](https://developer.android.com/build/releases/past-releases/agp-7-4-0-release-notes) for more details.

 enhancement: Update Android Gradle Plugin version to `7.4.2`

---

course/src/main/AndroidManifest.xml
samples/build.gradle

- The app crashes when downloading a video on Android 14 because, if the app targets Android 14, it must specify appropriate foreground service types.
- This commit addresses the issue by specifying the required foreground service types. [Foreground service types are required](https://developer.android.com/about/versions/14/changes/fgs-types-required), [Data sync](https://developer.android.com/about/versions/14/changes/fgs-types-required#data-sync).

fix: App crash on downloading the video on Android 14

---

build.gradle
mobilertc/build.gradle

- Resolved build failure by addressing issues with deprecated dependencies.
- The `com.theartofdev.edmodo:android-image-cropper:2.8.0` package, which is no longer maintained and removed from repositories, has been temporarily published to our GitHub account and used in the project to resolve the issue.
- Updated the `com.google.android:flexbox:2.0.1` package, which has been removed and replaced with `com.google.android.flexbox:flexbox:3.0.0` in the latest version. This update was applied in the mobilertc `build.gradle` file, following Zoom's suggested changes. More details can be found on the Zoom community issue [here](https://devforum.zoom.us/t/could-not-resolve-com-google-android2-0-1-for-zoom-sdk-android-5-17-11-20433/115918).

fix: Build fails due to deprecated dependencies

---

course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java

- Previously, the secure window was applied to all video content by default, preventing screenshots regardless of the institute settings.
- In this commit, we modified the behavior to enable or disable the secure window based on the `ScreenshotDisabled` field in the `InstituteSettings` model.

fix: Unable to take screenshots even with prevent screenshots disabled in the portal.

---

core/src/main/java/in/testpress/ui/AbstractWebViewActivity.kt
course/src/main/java/in/testpress/course/ui/ChaptersListFragment.java
course/src/main/java/in/testpress/course/ui/MyCoursesFragment.java
exam/src/main/java/in/testpress/exam/ui/ReviewQuestionsFragment.java
samples/src/main/java/in/testpress/samples/course/CourseSampleActivity.java

- This update allows external URLs (non-institute URLs) to be opened in the webview while keeping authentication enabled.
- This change is needed because the Catking app uses external URLs that require secure access with authentication.

enhancement: Add option to open non-institute URLs with authentication enabled

---

core/src/main/java/in/testpress/util/webview/CustomWebViewClient.kt

- Previously, errors were displayed for every error that occurred within the WebView, including errors from loading static image URLs and other resources.
- In this commit, we added validation to selectively display errors in the WebView, ensuring that only relevant errors are shown to users.
- This commit does not handle error display for failures related to static image URLs or other non-critical resources.

fix: Add validation for WebView errors

---

build.gradle
core/src/main/java/in/testpress/util/Misc.kt
core/src/main/java/in/testpress/util/extension/Activity.kt
exam/src/main/AndroidManifest.xml
exam/src/main/java/in/testpress/exam/ui/TestQuestionFragment.java
exam/src/main/res/values/strings.xml
samples/build.gradle
samples/src/main/java/in/testpress/samples/MainActivity.java

- On Android 13 and higher, users were unable to upload files in File type questions due to missing permissions. Specifically, `READ_MEDIA_IMAGES` and `READ_MEDIA_VIDEO` permissions were required, and for Android 14, the `READ_MEDIA_VISUAL_USER_SELECTED` permission was needed to access files and photos.
- In this commit, we added runtime permission requests for these permissions when users attempt to upload files.
- If the user denies the permission, a snackbar message is displayed to inform them that permission is required to perform the action.

fix: Unable to upload files in File type questions on Android 13 and higher

---

core/src/main/java/in/testpress/ui/BaseToolBarActivity.kt

- This PR fixes an issue in `BaseToolBarActivity` where the overridden `setContentView` method did not accept a nullable View. Although `super.setContentView(view)` can handle a nullable `View?`, the previous override enforced a non-nullable View. This caused issues when passing null values, potentially leading to build failures. Ref - [Docs](https://www.jot.fm/issues/issue_2005_03/column2/#:~:text=An%20inheritance%20conflict%20arises%20when,accidental%20and%20recombinant%20inheritance%20conflicts.)

fix: Resolve Inheritance Conflict Resolution Error

---

course/build.gradle

- Added the missing `com.google.android.flexbox:flexbox:3.0.0` dependency in `course/build.gradle`.
- The Zoom SDK internally includes Flexbox, so the dependency issue arises only when the Zoom SDK is disabled.
- This fix ensures that Flexbox is available independently of whether the Zoom SDK is enabled or not.

fix: Missing Flexbox dependency when Zoom SDK is disabled

---

exam/src/main/java/in/testpress/exam/ui/TestFragment.java

- Previously, the exam countdown timer was initialized multiple times on every successful questions API call for a different page. As a result, multiple timers were active simultaneously, causing multiple sections to end at the same time.
- To resolve this, we're now checking for an existing timer and canceling it before creating a new instance, preventing multiple countdowns from running simultaneously. This change ensures that each section's timer functions correctly and independently, aligning with the exam's intended flow.

fix: Prevent multiple initializations of exam countdown timer

---

course/src/main/java/in/testpress/course/helpers/CourseLastSyncedDate.kt

- The `TestpressSession` is null when initializing CourseLastSyncedDate, leading to a crash.
- In this commit, `TestpressSession` is made a nullable value, and validation is added before accessing the institute settings from it.

fix: App crash caused by null TestpressSession during initialization

---

course/src/main/java/in/testpress/course/fragments/DocumentViewerFragment.kt

- Fixed a crash that occurred when closing the PDF viewer before the download was complete.
- Added logic to cancel the PDF download and clean up partially downloaded files when the back button is pressed.

fix: App crash when quickly opening and closing PDF Content

---

course/src/main/java/in/testpress/course/fragments/VideoConferenceFragment.kt

- The app crashes when the user rapidly opens and closes the Video Conference screen because the asynchronous Zoom SDK initialization attempts to update the UI after the fragment is closed.
- Added a visibility check in `hideLoadingAndEnableStartButton` to ensure the fragment is still visible before updating the UI.

fix: App crash when quickly opening and closing Video Conference screen

---

course/src/main/java/in/testpress/course/TestpressCourse.java
course/src/main/java/in/testpress/course/ui/CourseListFragment.java

- This update introduces the ability to filter courses by tags when opening the `CourseListActivity`. The `TestpressCourse.show()` method has been updated to accept a list of tags as a parameter, which are passed to the `CourseListActivity` via an intent extra. This allows courses to be filtered based on the provided tags when the activity is started.
- Additionally, a helper method `getMyCoursesFragment()` was added to simplify fragment creation in `CourseListFragment`.

enhancement: Add course filtering by tags in TestpressCourse

---

core/src/main/java/in/testpress/models/greendao/Course.java
core/src/main/java/in/testpress/network/TestpressApiClient.java
course/src/main/java/in/testpress/course/TestpressCourse.java
course/src/main/java/in/testpress/course/ui/MyCoursesFragment.java

- This update introduces the ability to exclude courses by tags when opening the `CourseListActivity`. The `TestpressCourse.show()` method has been updated to accept a list of excludeTags as a parameter, which are passed to the `CourseListActivity` via an intent extra. This allows courses to be filtered based on the provided tags when the activity is started.

enhancement: Add exclude tags feature for course filtering

---

course/src/main/java/in/testpress/course/repository/ContentsRepository.kt

- When users access the content list without an internet connection, the app displays content from the local database. However, the content order was previously not sorted based on the `order` field in the `Content` model.
- This commit resolves the issue by adding a sorting operation to the query that retrieves content from the local database, ensuring the list is properly ordered.

fix: Ensure correct content list order in offline mode

---

exam/src/main/java/in/testpress/exam/ui/TestFragment.java

- In commit 8270379, we removed the code that dismissed the dialog and started the timer. This removal was intended to prevent the timer from being initialized multiple times.
- While we handled the multiple initializations issue, removing this code introduced a new problem where the exam could not resume properly.
- In this commit, we reintroduced the code with a validation to ensure it only triggers during the `UPDATE_ANSWER` process, addressing the issue without reintroducing the original problem.

fix: Unable to resume the exam after pausing due to no internet connection

---

exam/src/main/java/in/testpress/exam/ui/TestActivity.java

- Fixed a crash that occurred when pressing the back button on the Review Stats screen in low-memory scenarios. 
- The issue arose because TestActivity was recreated, and while the Exam object was restored from savedInstanceState, it was not reassigned to examViewModel.
- This commit ensures the examViewModel is updated during activity recreation, preventing the crash and maintaining consistent state.

fix: App crash while navigating back from review stats page

---

course/src/main/java/in/testpress/course/fragments/LiveStreamFragment.kt

- We had not implemented the attempt creation process for live stream content, which prevented tracking users' live stream consumption.
- In this commit, we added an API call for attempt creation that triggers when a user starts viewing a live stream.

fix: Chapter content attempts are not being created

---

exam/src/main/java/in/testpress/exam/repository/AttemptRepository.kt

- If the "Enforce Continuous Timer" option is enabled in the exam, the timer is handled on the backend. On Android, the timer often experiences delays, causing a time gap.
- When the exam timer ends on the mobile device, the app attempts to save the last answer. However, if the backend has already marked the exam as ended, the API returns a 403 error.
- This PR introduces a condition to handle 403 errors with an "exam already ended" message from the API.
- If this condition is satisfied, the app updates the last attempt item locally and ends the exam gracefully.

fix: Handle unauthenticated errors for ended exams

---

core/src/main/java/in/testpress/core/TestpressSdk.java
core/src/main/java/in/testpress/fragments/WebViewFragment.kt

Ensures that webview sessions are cleared upon logout to prevent session leakage between users.
The following changes were made:
- Added logic to clear cookies and web storage in the `onLogout()` method in `TestpressSdk.java` to remove session data.
- In `WebViewFragment.kt`, added cache and history clearing for the WebView to prevent previous session data from being reused.
This fixes the issue where a second user on the same device could access the first user's session data when navigating to the WebView after logout.

fix: Clear webview session on logout to prevent session leaks

---

core/src/main/java/in/testpress/core/TestpressException.java
core/src/main/java/in/testpress/fragments/EmptyViewFragment.kt
core/src/main/java/in/testpress/util/webview/CustomWebViewClient.kt

Improved error handling for WebView to differentiate and debug unexpected errors effectively.
The following changes were made:
- Added a new `Kind.WEBVIEW_UNEXPECTED` type in `TestpressException` to classify unexpected WebView errors separately.
- Created a new method `unexpectedWebViewError()` in `TestpressException` for generating exceptions of this kind.
- Introduced the `isWebViewUnexpectedError()` helper method to identify WebView-specific unexpected errors.
- Updated `EmptyViewFragment` to handle `WEBVIEW_UNEXPECTED` errors explicitly with a dedicated `handleWebViewUnknownError()` method.
- Modified `CustomWebViewClient` to provide error details (e.g., error code) in the exception message for better debugging.
This change ensures that WebView errors are not conflated with other …

feat: Add specific handling for unexpected WebView errors

---

core/src/main/java/in/testpress/models/greendao/Chapter.java
core/src/main/java/in/testpress/models/greendao/Course.java
course/src/main/java/in/testpress/course/pagers/ChapterPager.java
course/src/main/java/in/testpress/course/ui/ChapterDetailActivity.java
course/src/main/java/in/testpress/course/ui/ChaptersListAdapter.java
course/src/main/java/in/testpress/course/ui/ChaptersListFragment.java

- This PR addresses the inefficiency in fetching chapters for the chapter list. Previously, all chapters were fetched, and only the required root or child chapters were displayed to the user. This led to performance issues, especially with large datasets.
- Fetching only the necessary chapters (root or child) from the database or API.
- Introducing methods to retrieve child chapters directly based on the parent ID.
- Modifying the logic in chapter-related classes (Chapter, ChapterPager, etc.) to support the optimized fetching.

fix: Optimize chapter fetching to load only required chapters

---

course/src/main/java/in/testpress/course/fragments/LiveStreamFragment.kt

- This PR resolves the issue where users were required to manually enter their name every time they accessed the live stream chat. This was caused by not passing the JWT token in the WebView request, which prevented automatic user authentication.
- Updating the IS_AUTHENTICATION_REQUIRED flag to true when opening the WebView for the live stream chat.
- With this change, users will no longer need to re-enter their details, and the chat screen will validate and load automatically, enhancing the user experience.

fix: Pass JWT token for authentication in live stream chat WebView

---

course/src/main/java/in/testpress/course/ui/ChapterDetailActivity.java

This PR removes the automatic data load in onResume to avoid redundant API calls when returning to the content list view. Users can now manually refresh the data using the swipe-to-refresh option.

fix: Prevent redundant data load on resume in ChapterDetailActivity

---

course/src/main/java/in/testpress/course/ui/AvailableCourseListFragment.java

This commit removes the unnecessary category API call that was being triggered each time the app came to the foreground. Instead, the category data is now refreshed only when the user performs a swipe-to-refresh action.

fix: Remove redundant category API call and add refresh on swipe

---

course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java

- This update addresses the issue of redundant API calls triggered during ExoPlayer initialization due to the seek callback being invoked when the start time is set.
- Introduced a firstSeekCalled flag to skip the API call during the first invocation of onSeekProcessed.
Ensured the seek callback only triggers the user attempt API call on subsequent seeks, avoiding unnecessary calls during initialization.
- Preserved the existing behavior for user interactions while improving efficiency.
- These changes optimize the initialization process and reduce unnecessary server requests, enhancing the overall app performance.

fix: Prevent redundant API calls during ExoPlayer initialization

---

course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java

- Moved the seekHandler declaration to the top of the class alongside other global variables.

refactor: Move seekHandler declaration to class-level for cleaner structure

---

course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java

- This fix ensures that playback errors are not shown to users when the watch duration update API fails, as it is not critical to the playback experience.
- Removed the errorOnVideoAttemptUpdate flag and associated logic.
- Updated the condition to only handle errors relevant to playback state.
- This change improves the user experience by preventing irrelevant errors from being displayed on the player.

fix: Remove unnecessary error display for watch duration API failure

---

course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java
course/src/main/java/in/testpress/course/util/WatermarkOverlay.kt

- This update addresses user experience issues with the watermark overlay
- Reduced watermark text size from 32f to 30f for less obtrusion.
- Increased animation duration from 7500ms to 30000ms to slow down the movement, making it less distracting.
- Changed the overlay text priority to display username over email when available.
- These changes ensure the watermark remains effective while being less intrusive to users.

fix: Improve watermark appearance and animation for better user experience

---

course/src/main/java/in/testpress/course/fragments/DownloadsFragment.kt

Previously, deleted videos remained visible for users to attempt deletion again with no effect, because the adapter not update when the list became empty, leading to stale data when reopening the screen. This was caused by the adapter update being placed after the empty screen logic in the observer, causing it to be skipped.
Moved the adapter update to the top of the observer to ensure the UI remains consistent and reflects deletions correctly.

fix: Prevent stale data display when downloads list is empty

---

core/src/main/java/in/testpress/util/PermissionsUtils.java
exam/src/main/AndroidManifest.xml

- The app was requesting storage permissions on Android 10 and higher, where the permission is no longer necessary.
- This permission was used for features allowing users to download attachments and review PDF files directly to the external download directory. However, starting with Android 10, the permission is no longer required.
- The permission check was updated to restrict storage access to devices with SDK <= P (Android 9), and the manifest was revised to request the permission only for devices with SDK <= 28. [Reference](https://developer.android.com/reference/android/app/DownloadManager.Request#setDestinationInExternalPublicDir(java.lang.String,%20java.lang.String))

fix: Remove unnecessary storage permission for Android 10 and above

---

core/src/main/java/in/testpress/models/ProfileDetails.java
course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java

- Playback error logs lacked user-specific context, such as the username or package name, which would help in filtering and identifying issues.
- So user-specific details such as username and packageName are now included in the playback error logs, making it easier to filter and analyze issues.

fix: Improve playback error logging with user details

---

core/schemas/in.testpress.database.TestpressDatabase/30.json
core/src/main/java/in/testpress/database/Room.kt
core/src/main/java/in/testpress/database/dao/ContentLiteDao.kt
core/src/main/java/in/testpress/database/entities/ContentEntityLite.kt
core/src/main/java/in/testpress/database/roommigration/RoomMigration29To30.kt
course/src/main/java/in/testpress/course/pagination/CourseContentsRemoteMediator.kt

- The app sorts content based on the start date, but some entries have `start = null`.
- If any first-page content has a null start date, pagination gets stuck in an infinite loop.
- The pagination logic uses `sortedByDescending { it.start }`, but null values disrupt sorting.
- The last item retrieved may not be the correct last item, causing the second page to refetch indefinitely.
- Removed sorting by start date while fetching the last item in `getRemoteKeyForLastItem()`.
- Introduced an auto-incrementing `contentOrder` column in `RunningContentEntity` to maintain a consistent order.
- Updated Room migration (v29 → v30) to add `contentOrder` as the primary key.

fix: Prevent infinite pagination loop due to null start date

---

course/src/main/java/in/testpress/course/repository/CourseContentsRepository.kt

- The app was making 3 unnecessary API calls during initial content load on running content and upcoming content list views, causing increased server load. This was happening because Paging library's default behavior loads 3× the page size on initialization. By aligning the initial load size with our API's page size of 20, we now make two API calls, reducing server load while still maintaining smooth content delivery.

perf: Optimize course running and upcoming list screen

---

exam/src/main/java/in/testpress/exam/ui/TestActivity.java

- If a user starts an exam and then force-closes the app, there is no way to determine the exam's status.
- As a result, the "Resume" button may not appear correctly on the exam detail screen.
- The app does not track whether an exam was in progress when the app was closed.
- When a user starts an exam, the pausedAttemptsCount is set to 1 in the Exam entity.
- This value is then used in the exam detail screen to determine if the "Resume" button should be displayed.

fix: Track paused exam attempts to enable resume functionality

---

core/src/main/java/in/testpress/models/InstituteSettings.java

- A NullPointerException occurs when the url, baseUrl, or whiteLabeledHostUrl is null in the isInstituteUrl method.
- This leads to a crash when the String.contains() method is invoked on a null value.
- The contains() method was being called on potentially null objects, causing the exception when any of the arguments is null.
- Added null checks for url, baseUrl, and whiteLabeledHostUrl to ensure that the contains() method is only called when they are not null.
- This prevents the NullPointerException and ensures that the method behaves safely when handling null values.

fix: Prevent NullPointerException in isInstituteUrl method by adding null checks

---

course/src/main/java/in/testpress/course/fragments/VideoConferenceFragment.kt

- A NullPointerException was reported in VideoConferenceFragment at initializeVideoConferenceHandler, but it could not be reproduced consistently.
- The issue occurs in some cases where the videoConference object is unexpectedly null.
- Added Sentry logging to capture the exception along with user context (username, content ID, and content title) to track the issue more effectively.

fix: Log null pointer exception on video conference page in sentry

---

core/src/main/java/in/testpress/ui/UserActivityFragment.java

- A NullPointerException was occurring in UserActivityFragment.refreshAdapter() when calling getWrappedAdapter() on a null getListAdapter().
- This happened when refreshAdapter was called before the adapter was initialized.
- Added a null check to ensure getListAdapter() and getWrappedAdapter() are not null before clearing items and refreshing the adapter.

fix: Prevent NullPointerException in refreshAdapter of UserActivityFragment

---

course/src/main/java/in/testpress/course/fragments/BaseContentDetailFragment.kt
course/src/main/java/in/testpress/course/ui/ContentActivity.java

Added a new parameter `forceRefreshContent` in `ContentActivity` to allow forced content fetching. This ensures that content is refreshed explicitly when needed. Updated `BaseContentDetailFragment` to handle this new parameter while loading content.

enhancement: Add force fetch parameter to reload content

---

course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java

Added a null check for the ExoPlayer instance before calling seekTo(). This prevents crashes caused by attempting to seek when the player is not initialized. The issue occurred when videoWidgetFragment was not properly set up before seeking, leading to a NullPointerException.

fix: Prevent crash when seeking in ExoPlayer

---

course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java

Updated the throttling mechanism to apply even when an API request fails. Previously, throttling was only set for successful responses, which caused repeated API calls in case of failures. Now, a default throttling time of 60 seconds is applied when an API request fails, preventing excessive retries.

fix: Apply throttling for failed user video API requests

---

course/src/main/java/in/testpress/course/fragments/QuizQuestionFragment.kt
course/src/main/java/in/testpress/course/fragments/RootQuizFragment.kt

Fixed a crash occurring during activity recreation in low-memory conditions due to `quizOperationsCallback` being uninitialized. Changed it from `lateinit var` to a nullable variable and updated its usage to prevent `UninitializedPropertyAccessException`. This ensures the app gracefully handles callback availability after activity recreation.

fix: Handle quizOperationsCallback reinitialization after activity recreation

---

course/src/main/java/in/testpress/course/AvailableCourseListAdapter.java
course/src/main/java/in/testpress/course/ui/ChapterDetailActivity.java
course/src/main/java/in/testpress/course/ui/ChaptersListAdapter.java

- Implemented free preview for courses when users click on a product from the product list.
- If a product has multiple courses, it navigates to CoursePreviewActivity.
- If a product has only one course, it directly opens ChapterDetailActivity.
- Added an overload method in ChapterDetailActivity.createIntent to handle the "Buy Now" button visibility.
- Ensured that clicking a chapter correctly passes the product slug and shows the "Buy Now" button when applicable.

feat: Add free course preview for product list items

---

.github/workflows/release.yml

- Build actions were failing due to the deprecated `actions/cache@v2`.
- In this commit, we updated the action to `actions/cache@v3`, which resolves the issue.

fix: Resolve GitHub Actions build failures

---

course/src/main/java/in/testpress/course/ui/ChaptersListAdapter.java

- Updated the product slug check to ensure `productSlug != null && !productSlug.isEmpty()` before determining whether to show the "Buy Now" button.
- Prevents potential NullPointerException issues when navigating to `ChapterDetailActivity`.

fix: Prevent null productSlug from affecting chapter detail navigation

---

course/src/main/java/in/testpress/course/fragments/WebViewVideoFragment.kt

- Updated loadVideo method in WebViewVideoFragment to differentiate between video and non-video embedded content based on the fullscreen class.
- Video Embed Content: Wrapped in a videoWrapper to maintain a 16:9 aspect ratio.
- Non-Video Embed Content: Displayed in fullscreen without additional wrapping.

fix: Preserve fullscreen mode for embedded content in WebView

---

store/src/main/java/in/testpress/store/ui/ProductDetailsActivity.java

- Added a null and empty check for product.getImages() before accessing the first image URL.
- Prevents potential crashes when the product does not have any images.
- Ensures the displayImage method receives a valid (even if empty) URL instead of causing an IndexOutOfBoundsException.

fix: Prevent crash when product images list is empty in ProductDetailsActivity

---

store/src/main/java/in/testpress/store/data/model/NetworkImage.kt
store/src/main/java/in/testpress/store/data/model/NetworkProductListResponse.kt
store/src/main/java/in/testpress/store/data/model/NetworkProductLite.kt

- Introduced NetworkImage, NetworkProductLite, and NetworkProductListResponse models for handling API responses in the store module.
- Added extension functions to map network models to domain entities (asDomain() for NetworkImage and NetworkProductLite).
- Ensures a structured approach for transforming API responses into database-compatible models.
- Lays the groundwork for a more scalable and maintainable data layer in the store module.

feat: Add network models for product and image mapping in store module

---

store/src/main/java/in/testpress/store/data/model/NetworkProductCategory.kt

- Introduced NetworkProductCategory data model for handling category responses from the API.
- Added mapping functions to convert network models to ProductCategoryEntity domain entities.
- This lays the groundwork for syncing product categories from the backend to the local database.

feat: Add NetworkProductCategory model and mapping to domain entity

---

store/src/main/java/in/testpress/store/network/ProductService.java
store/src/main/java/in/testpress/store/network/StoreApiClient.java

- Removed the `getProductsList()` method from `ProductService` and `StoreApiClient` as it is no longer used in the current store flow. This cleanup improves code maintainability by eliminating dead code.

refactor: Remove unused products list API from store client

---

course/src/main/java/in/testpress/course/fragments/DomainRestrictedVideoFragment.kt

- Domain restricted videos were failing to load in WebView  
- Cached data was bypassing domain validation  
- Disabled WebView cache, storage, and history

fix: Resolve cache issue in domain restricted playback

---

build.gradle

- Updated in.payu:payu-checkout-pro dependency from previous version to 1.8.9
- New version unlocks additional banks that were missing earlier

build: Update payUCheckoutPro dependency to version 1.8.9

---

build.gradle

- Updated payu-checkout-pro from 1.9.0 to 2.0.1 to incorporate the latest features and improvements.

build: Upgrade payUCheckoutPro dependency to version 2.0.1

---

course/src/main/java/in/testpress/course/fragments/DocumentViewerFragment.kt
course/src/main/java/in/testpress/course/util/PDFDownloadManager.kt

- Verify PRDownloader status before invoking progress updates.
- Ensure downloadProgress is called only when download is running.
- Prevent NullPointerException in DocumentViewerFragment after view is destroyed.

fix: Prevent progress callback after cancel or complete

---

build.gradle

- Downgrade Razorpay SDK in the SDK module from 1.6.41 to 1.6.38.
- The app using this SDK was failing to compile due to unresolved references in the Google Credentials API caused by the updated transitive dependency on play-services-auth in Razorpay 1.6.41.
- This downgrade ensures the SDK provides a compatible play-services-auth version, fixing app compilation.

build: Downgrade Razorpay SDK to 1.6.38

---

core/src/main/res/values/color.xml
core/src/main/res/values/strings.xml
course/src/main/java/in/testpress/course/fragments/ContentLoadingFragment.kt
course/src/main/java/in/testpress/course/fragments/DocumentViewerFragment.kt
course/src/main/java/in/testpress/course/ui/ContentActivity.java
course/src/main/res/drawable/ask_ai_fab_background.xml
course/src/main/res/drawable/ic_ai.xml
course/src/main/res/layout/layout_document_viewer.xml

- Changed flow so AI-enabled PDFs open in DocumentViewerFragment by default instead of jumping straight to the AI PDF.
- Added a Floating Action Button (FAB) to switch to the AI PDF when needed.
- Updated navigation, layout, and resources to support this new flow.

feat: Add FAB to open AI chat PDF from standard viewer
