build.gradle, exam/build.gradle, exam/src/main/AndroidManifest.xml, exam/src/main/java/in/testpress/exam/models/ReviewAnswer.java, exam/src/main/java/in/testpress/exam/models/ReviewItem.java, exam/src/main/java/in/testpress/exam/models/ReviewQuestion.java, exam/src/main/java/in/testpress/exam/network/ExamService.java, exam/src/main/java/in/testpress/exam/network/ReviewQuestionsPager.java, exam/src/main/java/in/testpress/exam/network/TestpressExamApiClient.java, exam/src/main/java/in/testpress/exam/ui/AttemptsListAdapter.java, exam/src/main/java/in/testpress/exam/ui/HistoryListAdapter.java, exam/src/main/java/in/testpress/exam/ui/PagedItemFragment.java, exam/src/main/java/in/testpress/exam/ui/ReviewActivity.java, exam/src/main/java/in/testpress/exam/ui/ReviewFragment.java, exam/src/main/java/in/testpress/exam/ui/ReviewListAdapter.java, exam/src/main/java/in/testpress/exam/ui/ReviewPagerAdapter.java, exam/src/main/java/in/testpress/exam/ui/ReviewQuestionsFragment.java, exam/src/main/java/in/testpress/exam/ui/ReviewStatsFragment.java, exam/src/main/java/in/testpress/exam/ui/TestActivity.java, exam/src/main/java/in/testpress/exam/ui/TestFragment.java, exam/src/main/res/drawable/testpress_round_background.xml, exam/src/main/res/drawable/testpress_round_green_background.xml, exam/src/main/res/drawable/testpress_round_red_background.xml, exam/src/main/res/layout-xlarge/testpress_review_stats.xml, exam/src/main/res/layout/testpress_fragment_review.xml, exam/src/main/res/layout/testpress_fragment_review_question.xml, exam/src/main/res/layout/testpress_review_answer.xml, exam/src/main/res/layout/testpress_review_stats.xml, exam/src/main/res/values/color.xml, exam/src/main/res/values/strings.xml
For completed attempts user can review the stats & questions &
explanations if available.
=> Implement review

exam/src/main/java/in/testpress/exam/ui/TestFragment.java
Subject dropdown will be shown if number of subjects > 1, irrespective
of IBPS template.
Fixed #20
=> Show subject dropdown if #subject > 1

core/src/main/java/in/testpress/core/TestpressSdk.java, core/src/main/java/in/testpress/util/UIUtils.java, exam/src/main/java/in/testpress/exam/ui/AttemptsListAdapter.java, exam/src/main/java/in/testpress/exam/ui/AvailableExamsListAdapter.java, exam/src/main/java/in/testpress/exam/ui/EmailPdfDialog.java, exam/src/main/java/in/testpress/exam/ui/HistoryListAdapter.java, exam/src/main/java/in/testpress/exam/ui/PagedItemFragment.java, exam/src/main/java/in/testpress/exam/ui/ReviewFragment.java, exam/src/main/java/in/testpress/exam/ui/ReviewStatsFragment.java, exam/src/main/java/in/testpress/exam/ui/SearchFragment.java, exam/src/main/java/in/testpress/exam/ui/TestActivity.java, exam/src/main/java/in/testpress/exam/ui/TestFragment.java, exam/src/main/java/in/testpress/exam/util/ViewUtils.java
SetLeftDrawable method is moved to ViewUtils.
SetIntermidiateDrawable is moved to UIUtils in core module.
Fixes #23, #24.
=> Replace common methods as util functions

exam/src/main/java/in/testpress/exam/ui/AvailableExamsListAdapter.java, exam/src/main/java/in/testpress/exam/ui/ReviewStatsFragment.java, exam/src/main/java/in/testpress/exam/ui/TestQuestionFragment.java, exam/src/main/res/layout-xlarge/testpress_activity_test.xml, exam/src/main/res/layout-xlarge/testpress_review_stats.xml, exam/src/main/res/layout/available_exams_list_item.xml, exam/src/main/res/layout/history_exams_list_item.xml, exam/src/main/res/layout/testpress_activity_test.xml, exam/src/main/res/layout/testpress_attempts_list_item.xml, exam/src/main/res/layout/testpress_fragment_test_engine.xml, exam/src/main/res/layout/testpress_fragment_test_question.xml, exam/src/main/res/layout/testpress_radio_button.xml, exam/src/main/res/layout/testpress_review_answer.xml, exam/src/main/res/layout/testpress_review_question.xml, exam/src/main/res/layout/testpress_review_stats.xml, exam/src/main/res/layout/testpress_test_panel_list_item.xml, exam/src/main/res/layout/upcoming_exams_list_item.xml, exam/src/main/res/values/strings.xml, exam/src/main/res/values/styles.xml
Text style of question & options in test engine & review are modified.
They can be customisable by overriding their theme in styles.xml.
Modified some layouts to support different font & screen sizes.
=> Modify text style for question & options in test engine & review

exam/src/main/java/in/testpress/exam/models/Exam.java, exam/src/main/java/in/testpress/exam/ui/HistoryListAdapter.java, exam/src/main/res/layout/history_exams_list_item.xml, gradle.properties
=> Hide review button if "show answers" option disabled

core/src/main/java/in/testpress/models/greendao/Video.java, core/src/main/java/in/testpress/models/greendao/VideoAttempt.java, core/src/main/java/in/testpress/models/greendao/VideoDao.java, course/src/main/java/in/testpress/course/network/CourseService.java, course/src/main/java/in/testpress/course/network/TestpressCourseApiClient.java, course/src/main/java/in/testpress/course/ui/ContentActivity.java, course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java, course/src/test/java/in/testpress/course/util/ExoPlayerUtilTest.java, testpressdaogenerator/src/main/java/in/testpress/TestpressSDKDaoGenerator.java
-  Updated videoWatchedPercentage field of content on video attempt update for every 3 secs.
- To display updated video watched percentage on backpress from content detail after watching the video.
=> Update videoWatchedPercentage on video attempt update on every 3 secs

course/src/main/java/in/testpress/course/ui/ContentActivity.java, course/src/main/java/in/testpress/course/ui/ExoPlayerActivity.java, course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java, course/src/main/java/in/testpress/course/util/ExoplayerFullscreenHelper.java, samples/src/main/java/in/testpress/samples/core/TestpressCoreSampleActivity.java
- Added OrientationEventListener to detect the phone rotation. 
- Now video will go fullscreen mode according to phone orientation.
- Earlier, the video does not go to fullscreen mode on changing the phone orientation.
=> Add Exoplayer fullscreen feature on phone rotation.

store/src/main/java/in/testpress/store/TestpressStore.java, store/src/main/java/in/testpress/store/ui/ProductsListActivity.java
- Add option to set the dynamic title for the products list activity base bar
- Earlier title was hardcoded for the product list.
=> Add dynamic label to product title bar

core/src/main/java/in/testpress/core/TestpressSdk.java, core/src/main/java/in/testpress/network/AuthorizationErrorResponse.java
- Add support to display username field error during authentication
- By this user can get to know if there is an error in username
=> Add support to display username field error

core/src/main/res/values/styles.xml, samples/src/main/res/values/styles.xml
- Set the primary color for status bar
- To improve UI
=> Set primary color for status bar

core/src/main/java/in/testpress/core/TestpressSdk.java, core/src/main/java/in/testpress/network/AuthenticationService.java, core/src/main/java/in/testpress/network/TestpressApiClient.java, exam/build.gradle
- On logout, logout API should be called, this will clear the user session in visitor list.
- Part of parallel login restriction feature
=> Call Logout API on logout

core/src/main/java/in/testpress/models/InstituteSettings.java, core/src/main/java/in/testpress/network/TestpressApiClient.java, core/src/main/java/in/testpress/util/UIUtils.java, core/src/main/res/values/strings.xml
- Display alert on max login limit exceeded error.
- User can get insight if why the app is inaccessible.
=> Display alert on max login limit exceeded error

core/src/main/java/in/testpress/core/TestpressRetrofitRequest.java, core/src/main/java/in/testpress/network/BaseResourcePager.java, core/src/test/java/in/testpress/network/TestBaseResourcePager.java, core/src/test/java/in/testpress/util/SamplePager.java
- Added support to fetch items asynchronous in base pager
No of test cases - Existing test cases
=> Add method to fetch items async in pager

core/src/main/java/in/testpress/models/greendao/Course.java, course/src/main/java/in/testpress/course/ui/ChaptersListFragment.java
- Added hasChapters method to course
- Used hasChapters method to check if course has chapters
=> Use hasChapters method to check if course has chapters

core/src/main/java/in/testpress/models/greendao/Content.java, course/src/main/java/in/testpress/course/ui/ContentActivity.java
- Refactor checkContentType method in ContentActivity.
- Moved code to appropriate functions
=> Refactor checkContentType method in ContentActivity

core/src/main/java/in/testpress/models/greendao/Chapter.java, course/src/main/java/in/testpress/course/ui/ChapterDetailActivity.java
- Added hasChildren and hasContents method in Chapter
- Used hasChildren and hasContents method in appropriate places
=> Add hasChildren and hasContents method in Chapter

course/src/main/java/in/testpress/course/network/CourseService.java, course/src/main/java/in/testpress/course/network/TestpressCourseApiClient.java, course/src/main/java/in/testpress/course/ui/ChapterDetailActivity.java
- If the user goes directly to the chapter detail page through deeplinking course may not be available, so it checked and loaded.
=> Load course if not available in chapters list or detail

core/src/main/java/in/testpress/models/greendao/Chapter.java, core/src/main/java/in/testpress/models/greendao/Course.java, course/src/main/java/in/testpress/course/ui/ChapterDetailActivity.java, course/src/main/java/in/testpress/course/ui/ChaptersListAdapter.java, course/src/main/java/in/testpress/course/ui/ChaptersListFragment.java
- Used children from chapters instead of using getParentChaptersQueryBuilder.
=> Replace getParentChaptersQueryBuilder usage

core/src/main/java/in/testpress/models/greendao/Chapter.java, course/src/main/java/in/testpress/course/network/TestpressCourseApiClient.java, course/src/main/java/in/testpress/course/ui/ChapterDetailActivity.java, course/src/main/java/in/testpress/course/ui/ContentActivity.java, course/src/main/java/in/testpress/course/ui/ContentsListAdapter.java, course/src/main/java/in/testpress/course/ui/ContentsListFragment.java, course/src/main/java/in/testpress/course/ui/CourseListAdapter.java, exam/src/main/java/in/testpress/exam/ui/TestFragment.java
=> Change courses API to 2.4

build.gradle, core/build.gradle, core/src/main/java/in/testpress/ui/BaseListViewFragment.java, core/src/main/res/layout/testpress_list.xml, core/src/main/res/layout/testpress_list_placholder.xml, course/build.gradle, course/src/main/java/in/testpress/course/ui/ChaptersListFragment.java
- Show shimmer effect on chapters load
=> Show shimmer effect on chapters load

course/src/main/java/in/testpress/course/ui/CourseListActivity.java, course/src/main/java/in/testpress/course/ui/CourseListFragment.java, course/src/main/res/values/strings.xml
- Till now only User's courses are being displayed by default, to display available courses for purchase also parent fragment with view pager is needed.
- CourseListFragment with view pager as MyCourses is added for now.
=> Display CourseListFragment by default

course/src/main/java/in/testpress/course/AvailableCourseListAdapter.java, course/src/main/java/in/testpress/course/TestpressCourse.java, course/src/main/java/in/testpress/course/ui/ChapterDetailActivity.java, course/src/main/java/in/testpress/course/ui/ChaptersGridFragment.java, course/src/main/java/in/testpress/course/ui/ChaptersListAdapter.java, course/src/main/java/in/testpress/course/ui/ChaptersListFragment.java, course/src/main/java/in/testpress/course/ui/ContentsListAdapter.java, course/src/main/java/in/testpress/course/ui/ContentsListFragment.java, course/src/main/java/in/testpress/course/ui/CourseListAdapter.java
- Display product detail page on clicking premium content.
=> Show product detail on clicking premium product

course/src/main/java/in/testpress/course/ui/ContentActivity.java, course/src/main/java/in/testpress/course/ui/ContentsListAdapter.java
- Hide navigation for content preview
=> Hide navigation for content preview

core/src/main/java/in/testpress/models/InstituteSettings.java, course/src/main/java/in/testpress/course/ui/CourseListFragment.java, samples/src/main/java/in/testpress/samples/course/CourseSampleActivity.java
- Show course products tab title from institute
=> Show course products tab title from institute

course/src/main/java/in/testpress/course/ui/ContentsListAdapter.java
- Display lock icon on schedule content and disable click
=> Show lock icon on scheduled content

core/src/main/java/in/testpress/core/TestpressSDKDatabase.java, core/src/main/java/in/testpress/v2_4/models/ContentsListResponse.java, course/src/main/java/in/testpress/course/network/ContentPager.java, course/src/main/java/in/testpress/course/network/CourseService.java, course/src/main/java/in/testpress/course/network/TestpressCourseApiClient.java, course/src/main/java/in/testpress/course/ui/ContentsListFragment.java
- Parse 2.4 contents API accordingly to the response
- 2.4 contents API result format is changed in backend
=> Parse contents 2.4 API accordingly

core/src/main/java/in/testpress/models/greendao/Content.java, core/src/main/java/in/testpress/models/greendao/ContentDao.java, testpressdaogenerator/src/main/java/in/testpress/TestpressSDKDaoGenerator.java
- Made Chapter as a relation to Content, with this chapter for specific content can be easily accessed with content.getChapter()
=> Add chapter relation to content

course/src/main/java/in/testpress/course/ui/CourseListAdapter.java, course/src/main/res/layout/testpress_course_list_item.xml
- Displayed Chapters and Contents count in the courses list
=> Display Chapters and Contents count in course list

course/src/main/java/in/testpress/course/network/TestpressCourseApiClient.java, course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java
- Changed user_videos_attempt update API to 2.4 since 2.4 API has throttling enabled
=> Change user_videos API to 2.4

course/src/main/java/in/testpress/course/ui/ContentActivity.java, course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java
- Removed periodic video content attempt 
- Update video content attempt when the video is seeked or play/pause
- Update video content attempt when next/prev button is pressed
=> Update video content attempt on seek and next/prev

.travis.yml, build.gradle, core/build.gradle
- Increased support library version to 28.0.0
- Increased compiled SDK version to 28 since support library needs it
=> Bump support library to its final version

build.gradle, course/build.gradle, course/src/main/java/in/testpress/course/ui/fragments/BookmarkFragment.kt, course/src/main/res/layout/bookmark_fragment_layout.xml, gradle/gradle-mvn-push.gradle, samples/build.gradle
- Added separate fragment to bookmark content
=> Add fragment to bookmark content

course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java
- When background audio is played, video content will be paused
- When video content is played, background audio will be paused.
=> Pause background audio when video content is played

course/src/main/java/in/testpress/course/network/CourseService.kt, course/src/main/java/in/testpress/course/network/NetworkContentAttempt.kt, course/src/test/java/in/testpress/course/network/CourseNetworkTest.kt
- Added API to create content attempt.
- This API will give NetworkContentAttempt as result
No of test case - 1
=> Add API to create content attempt

course/src/main/java/in/testpress/course/repository/ContentRepository.kt, course/src/test/java/in/testpress/course/repository/ContentRepositoryTest.kt
- Added createContentAttempt method
- Added getContentFromDB method
- Added storeBookmarkIdToContent method
No of test cases - 3
=> Add db and api fetch methods to repository

course/src/main/java/in/testpress/course/viewmodels/ContentViewModel.kt, course/src/test/java/in/testpress/course/repository/ContentRepositoryTest.kt, course/src/test/java/in/testpress/course/viewmodels/ContentViewModelTest.kt
- Exposed repository methods as API in the view model
No of test cases - 3
=> Expose repository methods as API in the view model

course/src/main/java/in/testpress/course/fragments/BaseContentDetailFragment.kt, course/src/main/res/layout/base_content_detail.xml, course/src/test/java/in/testpress/course/fragments/BaseContentDetailFragmentTest.kt, course/src/test/java/in/testpress/course/util/GreendaoCleanupMixin.kt
- This fragment contains common code which is necessary for all type of content fragments
- Concrete content fragments should extend and implement display method 
No of test case - 5
=> Add base content detail fragment

course/src/main/java/in/testpress/course/fragments/AttachmentContentFragment.kt, course/src/main/res/layout/attachment_content_detail.xml, course/src/test/java/in/testpress/course/fragments/AttachmentContentFragmentTest.kt
- Added separate fragment for attachment content
No of test case - 2
=> Add separate fragment for attachment content

course/src/main/java/in/testpress/course/di/InjectorUtils.kt, course/src/main/java/in/testpress/course/domain/DomainContent.kt, course/src/main/java/in/testpress/course/domain/DomainHtmlContent.kt, course/src/main/java/in/testpress/course/fragments/HtmlContentFragment.kt, course/src/main/java/in/testpress/course/repository/ContentRepository.kt, course/src/main/res/layout/html_content_detail.xml, course/src/test/java/in/testpress/course/fragments/HtmlContentFragmentTest.kt, course/src/test/java/in/testpress/course/repository/ContentRepositoryTest.kt
- Added separate fragment for HTML content 
No of test cases - 2
=> Add separate fragment for html content

course/src/main/java/in/testpress/course/domain/DomainVideoContent.kt, course/src/main/java/in/testpress/course/fragments/DomainRestrictedVideoFragment.kt, course/src/main/java/in/testpress/course/fragments/NativeVideoWidgetFragment.kt, course/src/main/java/in/testpress/course/fragments/VideoContentFragment.kt, course/src/main/java/in/testpress/course/fragments/WebViewVideoFragment.kt, course/src/main/res/layout/content_detail_activity.xml, course/src/main/res/layout/native_video_widget.xml, course/src/main/res/layout/video_content_detail.xml, course/src/main/res/layout/video_webview.xml
- Added separate fragment for video content
=> Add separate fragment for video content

course/src/main/java/in/testpress/course/TestpressCourse.java, course/src/main/java/in/testpress/course/di/InjectorUtils.kt, course/src/main/java/in/testpress/course/fragments/BaseContentDetailFragment.kt, course/src/main/java/in/testpress/course/repository/AttachmentContentRepository.kt, course/src/main/java/in/testpress/course/repository/ContentRepository.kt, course/src/main/java/in/testpress/course/repository/HtmlContentRepository.kt, course/src/main/java/in/testpress/course/repository/VideoContentRepository.kt
- Added separate repositories for each content type
=> Add separate repositories for each content type

course/src/main/java/in/testpress/course/domain/DomainLanguage.kt, course/src/main/java/in/testpress/course/network/CourseService.kt, course/src/main/java/in/testpress/course/network/NetworkContentAttempt.kt, course/src/main/java/in/testpress/course/repository/ContentRepository.kt, course/src/main/java/in/testpress/course/repository/ExamContentRepository.kt, course/src/main/java/in/testpress/course/viewmodels/ContentViewModel.kt, course/src/main/java/in/testpress/course/viewmodels/ExamContentViewModel.kt, course/src/test/java/in/testpress/course/network/CourseNetworkTest.kt, course/src/test/java/in/testpress/course/repository/ContentRepositoryTest.kt, course/src/test/java/in/testpress/course/repository/ExamContentRepositoryTest.kt, course/src/test/java/in/testpress/course/viewmodels/ContentViewModelTest.kt, course/src/test/resources/content_attempts.json, exam/build.gradle, exam/src/main/java/in/testpress/exam/network/ExamService.kt, exam/src/test/java/in/testpress/exam/network/ExamNetworkTest.kt, exam/src/test/resources/languages.json
- Added methods to get languages, content attempts in the exam content view model
No of test case - 4
=> Add exam repository and view model

course/src/main/java/in/testpress/course/domain/DomainContent.kt, course/src/main/java/in/testpress/course/domain/DomainContentAttempt.kt, course/src/main/java/in/testpress/course/domain/DomainExamContent.kt, course/src/main/java/in/testpress/course/fragments/AttemptsListFragment.kt, course/src/main/java/in/testpress/course/fragments/BaseExamWidgetFragment.kt, course/src/main/java/in/testpress/course/fragments/ExamContentFragment.kt, course/src/main/java/in/testpress/course/fragments/ExamStartScreenFragment.kt, course/src/main/java/in/testpress/course/ui/ContentAttemptListAdapter.java, course/src/main/res/layout/attempts_list_view.xml, course/src/main/res/layout/exam_content_detail.xml, course/src/main/res/layout/exam_start_screen.xml
- Added separate fragment for Exam Content
=> Add separate fragment for Exam content

course/src/main/java/in/testpress/course/fragments/NativeVideoWidgetFragment.kt, course/src/main/java/in/testpress/course/fragments/VideoContentFragment.kt, course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java, course/src/main/java/in/testpress/course/util/PatterEditableBuilder.kt, course/src/main/res/drawable/ic_down_chevron.xml, course/src/main/res/drawable/ic_up_chevron.xml, course/src/main/res/layout/native_video_widget.xml, course/src/main/res/layout/testpress_exo_player_view.xml, course/src/main/res/layout/video_content_detail.xml
- Displayed description for video if available
- If the description contains timings in the format (HH:MM:SS) then on clicking that will go to that timing in the video
- Added 16:9 aspect ratio for exoplayer
=> Display description for video if available

exam/src/main/AndroidManifest.xml, exam/src/main/java/in/testpress/exam/ui/ReviewStatsFragment.java, exam/src/main/java/in/testpress/exam/ui/ShareToUnLockActivity.kt, exam/src/main/java/in/testpress/exam/ui/adapters/ShareToUnlockAdapter.kt, exam/src/main/res/drawable/ic_letter.xml, exam/src/main/res/layout/share_app_item.xml, exam/src/main/res/layout/share_to_unlock.xml, exam/src/main/res/values/strings.xml, exam/src/test/java/in/testpress/exam/ui/ShareToUnlockActivityTest.kt
- As a part of the growth hack, we need UI which will allow the user to share some content. And if user shares it we will allow them to continue.
No of test cases - 3
=> Add UI for share to unlock explanations

core/src/main/java/in/testpress/models/greendao/Exam.java, core/src/main/java/in/testpress/models/greendao/ExamDao.java, course/src/main/java/in/testpress/course/domain/DomainExamContent.kt, course/src/main/java/in/testpress/course/network/NetworkExamContent.kt, testpressdaogenerator/src/main/java/in/testpress/TestpressSDKDaoGenerator.java
- Added show analytics field in exam model
=> Add show analytics field in exam model

exam/src/main/java/in/testpress/exam/ui/ReviewStatsFragment.java, exam/src/main/java/in/testpress/exam/ui/ShareToUnLockActivity.kt, exam/src/main/res/drawable/ic_lock_white_21dp.xml, exam/src/main/res/layout/testpress_fragment_review_stats.xml
- Show only share button and hide both analytics and solutions button if user did not share the app
=> Hide both analytics and solutions button if not shared

core/src/main/java/in/testpress/ui/BaseToolBarActivity.java, core/src/main/res/layout/testpress_toolbar.xml, core/src/main/res/values/color.xml, exam/src/main/java/in/testpress/exam/ui/ReviewQuestionsActivity.java, exam/src/main/java/in/testpress/exam/ui/ReviewQuestionsFragment.java, exam/src/main/res/menu/testpress_share.xml
- Changed toolbar color of review questions to white
- Removed back button from left and added it to right end
- Instead of solutions(toolbar title) displayed logo
- Helps in marketing when users share screenshots of the app screen
=> Customise toolbar for review questions

core/src/main/assets/TestpressReview.js, core/src/main/java/in/testpress/util/WebViewUtils.java, exam/src/main/java/in/testpress/exam/ui/ReviewQuestionsFragment.java
- Add logo in solutions screenshot while share
- This way the screenshot which user shares will have app logo, which is a good marketing hack for us.
=> Add logo in solutions screenshot while share

core/src/main/java/in/testpress/models/InstituteSettings.java, exam/src/main/java/in/testpress/exam/ui/ReviewQuestionsActivity.java, exam/src/main/java/in/testpress/exam/ui/ReviewQuestionsFragment.java, exam/src/main/res/menu/testpress_share.xml
- Use growth hacks field for displaying toolbar customization
- Enable sharing review solutions only if growth hack is enabled
=> Use growth hacks field for displaying toolbar customisation

core/src/main/java/in/testpress/models/InstituteSettings.java, exam/src/main/java/in/testpress/exam/ui/ReviewStatsFragment.java, exam/src/main/java/in/testpress/exam/ui/ShareToUnLockActivity.kt
- Share solutions button will be displayed for the user in review solutions one time irrespective of growth hack
=> Show share button for first time irrespective of growth hack

core/src/main/java/in/testpress/ui/BaseToolBarActivity.java, core/src/main/java/in/testpress/util/UIUtils.java, core/src/main/java/in/testpress/util/ViewUtils.java, exam/src/main/java/in/testpress/exam/ui/TestFragment.java, exam/src/main/res/layout/testpress_fragment_test_engine.xml
- Displayed logo in exam attempt screen
- Added util method to load logo in imageview.
- Used this util method for existing commit(9be24849a2c14342903aa2dba06f2e9289638f91)
=> Display logo in exam attempt screen

course/src/main/java/in/testpress/course/fragments/HtmlContentFragment.kt, course/src/main/res/layout/html_content_detail.xml
- Since bottom navigation is fixed last few lines of notes are hidden.
- Added margin-bottom to notes so that those last few lines will be visible
=> Fix last few lines not displayed in notes

exam/src/main/java/in/testpress/exam/ui/ReviewQuestionsFragment.java, exam/src/main/res/drawable/ic_bookmark_border_black_24dp.xml, exam/src/main/res/layout/testpress_fragment_review_question.xml, exam/src/main/res/menu/testpress_share.xml
- Moved bookmark button to toolbar in review question screen
- By moving the bookmark button to toolbar we can have more space inside view
=> Move bookmark to toolbar in review questions

core/build.gradle, core/src/main/java/in/testpress/core/TestpressSdk.java, core/src/main/java/in/testpress/models/InstituteSettings.java, core/src/main/java/in/testpress/util/EventsTrackerFacade.kt, core/src/main/java/in/testpress/util/FBEventsTrackerFacade.kt, course/src/main/java/in/testpress/course/fragments/HtmlContentFragment.kt, exam/src/main/java/in/testpress/exam/ui/TestFragment.java, store/src/main/java/in/testpress/store/ui/OrderConfirmActivity.java, store/src/main/java/in/testpress/store/ui/ProductDetailsActivity.java
- This will allow us to track in-app events in facebook
=> Add facebook event tracking support for in app events

core/build.gradle, core/src/main/java/in/testpress/models/InstituteSettings.java, core/src/main/java/in/testpress/util/EventsTrackerFacade.kt, core/src/main/java/in/testpress/util/FirebaseEventsTrackerFacade.kt
- Added google analytics to track custom app events
=> Add google analytics integration for events tracking

core/build.gradle, core/src/main/java/in/testpress/models/InstituteSettings.java, core/src/main/java/in/testpress/util/BranchEventTrackerFacade.kt, core/src/main/java/in/testpress/util/EventsTrackerFacade.kt, samples/build.gradle
- Added Branch integration for tracking in app events
=> Add Branch integration for tracking in app events

core/src/main/java/in/testpress/models/greendao/Chapter.java, course/src/main/java/in/testpress/course/ui/ChapterDetailActivity.java, course/src/main/java/in/testpress/course/ui/ContentsListFragment.java
- If a course has a large number of contents it takes very long time to load contents.
- So instead of loading contents from course we are loading from chapter
=> Load contents from chapter instead of course

core/src/main/java/in/testpress/ui/BaseListViewFragmentV2.kt, core/src/main/res/layout/base_list_layout.xml, course/src/main/java/in/testpress/course/network/CourseService.kt, course/src/main/java/in/testpress/course/repository/ContentsRepository.kt, course/src/main/java/in/testpress/course/ui/ChapterDetailActivity.java, course/src/main/java/in/testpress/course/ui/ContentListFragment.kt, course/src/main/java/in/testpress/course/viewmodels/ContentsListViewModel.kt
- Used repository and view model for content list fragment
- After one page is loaded content will be available for user and remaining page will be loaded in background
=> Refactor content list fragment to use MVVM architechture

course/src/main/java/in/testpress/course/domain/DomainContent.kt, course/src/main/java/in/testpress/course/domain/DomainExamContent.kt, course/src/main/java/in/testpress/course/domain/DomainVideoContent.kt, course/src/main/java/in/testpress/course/repository/ContentsRepository.kt, course/src/main/java/in/testpress/course/ui/ContentListAdapter.kt, course/src/main/java/in/testpress/course/ui/ContentListFragment.kt, exam/src/main/res/layout/testpress_content_list_item.xml
- In content list fragment we have used repository pattern, but instead of using domain model we used DB model
- Content list adapter has hard dependency on DB model, so it is refactored in this commit
=> Use DomainContent in content list fragment

course/src/main/res/layout/quiz_start_screen.xml
- Since quiz start screen layout had nestedscrollview and it had fillview port as true, quiz start screen took whole screen.
- Cleaned up quiz start screen layout and removed unnecessary views
=> Fix quiz attempts list not displayed bug

course/src/main/java/in/testpress/course/fragments/QuizQuestionFragment.kt, course/src/main/java/in/testpress/course/fragments/QuizReviewFragment.kt, course/src/main/java/in/testpress/course/fragments/QuizSlideFragment.kt, course/src/main/java/in/testpress/course/ui/QuizActivity.kt, course/src/main/res/layout/quiz_container_layout.xml
- Displayed question number in toolbar of quiz
=> Display question number in toolbar of quiz

exam/src/main/java/in/testpress/exam/ui/ReviewStatsFragment.java, exam/src/main/res/layout/testpress_fragment_review_stats.xml
- Hidden total marks, total time, cut off, score, percentage, percentile in case of quiz exam in stats page
=> Hide total marks, time, cut off, score in quiz stats page

core/src/main/java/in/testpress/v2_4/models/ContentsListResponse.java, course/src/main/java/in/testpress/course/domain/DomainContent.kt, course/src/main/java/in/testpress/course/domain/DomainVideoConferenceContent.kt, course/src/main/java/in/testpress/course/fragments/ContentLoadingFragment.kt, course/src/main/java/in/testpress/course/fragments/VideoConferenceFragment.kt, course/src/main/java/in/testpress/course/network/NetworkContent.kt, course/src/main/java/in/testpress/course/network/NetworkVideoConferenceContent.kt, course/src/main/java/in/testpress/course/repository/ContentRepository.kt, course/src/main/java/in/testpress/course/repository/ContentsRepository.kt, course/src/main/java/in/testpress/course/ui/WebViewActivity.java, course/src/main/res/layout/video_conference_content_layout.xml
- Added support to open video conference join url in webview
=> Add support to open video conference content

course/src/main/java/in/testpress/course/fragments/VideoConferenceFragment.kt, course/src/main/res/layout/video_conference_content_layout.xml
- Removed provider in video conference fragment
=> Remove provider in video conference UI

build.gradle, course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java, course/src/main/java/in/testpress/course/util/TrackSelectionDialog.kt, course/src/main/res/layout/track_selection_dialog.xml, course/src/main/res/values/strings.xml
- Changed `ExtractorMediaSource` to `ProgressiveMediaSource`
- TrackSelectionView is depreceated in exoplayer 2.10, so added trackselectiondialog fragment for track selection
=> Update Exoplayer to 2.10.8

store/src/main/java/in/testpress/store/ui/ProductDetailsActivity.java, store/src/main/res/layout/testpress_product_details_content_scrolling.xml
- Removed categories in product detail page
- Removed empty line when there is no additional description is present
- Removed Date from the Product Detail Page
=> Remove Date, empty line and Category from Product Page

core/src/main/java/in/testpress/database/OfflineVideo.kt, core/src/main/java/in/testpress/database/OfflineVideoDao.kt, core/src/main/java/in/testpress/database/Room.kt, course/src/main/java/in/testpress/course/domain/DomainOfflineVideo.kt
-  Added room model entity to store data related to video and its download progress, state
=> Add offline video model to store downloaded video details

course/src/main/java/in/testpress/course/ui/VideoDownloadQualityChooserDialog.kt, course/src/main/java/in/testpress/course/util/ExoPlayerTrackNameProvider.kt
- Display human readable name for track selection
- 240p -> "Very Low"
- 360p -> "Low"
- 480p -> "High"
- 540p -> "High"
- 720p -> "HD"
- 1080p -> "HD1080"
=> Display human readable name for track selection

store/src/main/java/in/testpress/store/models/CouponCodeResponse.kt, store/src/main/java/in/testpress/store/models/ProductDetailResponse.kt
- Added Coupon Code Data class to get coupon code response
=> Add Coupon Code Data Class

course/src/main/java/in/testpress/course/fragments/DownloadsFragment.kt, course/src/main/java/in/testpress/course/repository/ContentsRepository.kt, course/src/main/java/in/testpress/course/repository/CourseRepository.kt
- Added missed changes for ab250fc
=> Fix import Error

store/src/main/java/in/testpress/store/models/ProductsList.kt
- Added Product List Data classes
=> Add Product List Data Classes

store/src/main/java/in/testpress/store/models/ProductsList.kt
- Refactored ProductList Data Class
=> Refactor Product List Data class

core/build.gradle
- Added Multidex Dependency
- the total number of references that can be invoked by the code within a single Dalvik Executable (DEX) bytecode file exceed 65536 [https://developer.android.com/studio/build/multidex]
=> Add Multidex Dependency

store/src/main/java/in/testpress/store/network/NetworkProduct.kt
- Added Network Product Data Class
=> Add Network Product Data Class

store/src/main/java/in/testpress/store/network/ProductService.java, store/src/main/java/in/testpress/store/network/TestpressStoreApiClient.java, store/src/test/java/in/testpress/store/network/ProductListNetworkTest.kt
=> Refactor Product Network

store/src/main/java/in/testpress/store/domain/DomainProduct.kt
- Added Domain Product Data Class
=> Add Domain Product Data Class

course/src/main/java/in/testpress/course/repository/ContentsRepository.kt
- Sorted the course content by order in ascending order
=> Display Course Contents in Ascending Order

course/src/main/res/layout/track_selection_dialog.xml, course/src/main/res/layout/video_download_dialog.xml
- Fixed the quality selection dialog 
- Unable to select the quality to download and watch the videos in tab
=> Fix quality selection dialog

core/src/main/java/in/testpress/database/Room.kt, gradle.properties
- Room migration for product list
=> Fix room migration not found error

core/src/androidTest/java/in/testpress/core/database/ProductListDbTestMixin.kt
- Refactored ProductListDbTestMixin
=> Refactor ProductListDbTestMixin

exam/src/main/java/in/testpress/exam/ui/ReviewPanelListAdapter.java
-Fixed a bug in displaying the question list.
- The question list displayed the questions as well as the HTML font script. The user should only able to see the questions.
=> Fix Review Question List UI

core/schemas/in.testpress.database.TestpressDatabase/3.json, core/src/androidTest/java/in/testpress/core/database/RoomMigrationsTest.kt, core/src/main/java/in/testpress/database/Room.kt, core/src/main/java/in/testpress/database/roommigration/RoomMigration3To4.kt
-added room database migration version 3 to 4
-Refactored Room migration unit test
Reason for change:
- Few apps sdk version are very old and now if we want to update the app to the latest sdk we need migration, the migration is added only for 4 to 6. so migration from 3 to 6 is added.
=> Add Room Migration version 3 to version 4

course/src/main/java/in/testpress/course/fragments/VideoContentFragment.kt
- showDownloadProgress displays not only the download progress also the status( downloaded, completed)
=> Rename showDownloadProgress to ShowDownloadStatus

exam/src/main/java/in/testpress/exam/domain/DomainComment.kt, exam/src/main/java/in/testpress/exam/network/NetworkComment.kt
-Added DomainComment data class 
-Added NetworkComment data class
=> Add DomainComment and NetworkComment Data Class

exam/src/main/java/in/testpress/exam/ui/ReviewPanelListAdapter.java, exam/src/main/java/in/testpress/exam/ui/ReviewQuestionsActivity.java, exam/src/main/java/in/testpress/exam/ui/TestFragment.java, exam/src/main/java/in/testpress/exam/ui/TestPanelListAdapter.java, exam/src/main/res/layout/testpress_test_panel_list_item.xml
Before the question is displayed in textview, so for the multi-language question, the HTML contents are displayed. Now we have added web view to display the question to solve this issue
=> Add webview to display question list

core/src/main/AndroidManifest.xml, core/src/main/java/in/testpress/util/CommonUtils.java, course/src/main/java/in/testpress/course/util/PDFViewer.kt
- To prevent users from sharing images of pdf, we are adding a watermark in it.
-  Watermark position is random. It will be changed for each page.
=> Display dynamic watermark on pdf

course/src/main/java/in/testpress/course/ui/viewholders/ExamContentListItemViewHolder.kt, exam/src/main/res/layout/exam_content_list_item.xml
- Displayed description for exams in contents list
=> Display description for exams in content list

course/src/main/java/in/testpress/course/services/VideoDownloadService.kt
- Downloads page will open on clicking the download notification
=> Fix navigate to download page on download notification click

core/schemas/in.testpress.database.TestpressDatabase/10.json, core/src/main/java/in/testpress/database/ContentEntity.kt, core/src/main/java/in/testpress/database/Room.kt, core/src/main/java/in/testpress/database/roommigration/RoomMigration9To10.kt, core/src/main/java/in/testpress/models/greendao/Content.java, core/src/main/java/in/testpress/models/greendao/ContentDao.java, course/src/main/java/in/testpress/course/domain/DomainContent.kt, course/src/main/java/in/testpress/course/network/NetworkContent.kt, course/src/main/java/in/testpress/course/ui/ContentListAdapter.kt, course/src/main/java/in/testpress/course/ui/viewholders/BaseContentListItemViewHolder.kt, testpressdaogenerator/src/main/java/in/testpress/TestpressSDKDaoGenerator.java
- Show info for ended contents in content list.
- Show lock and disallow user from seeing ended contents detail
=> Show info for ended contents in content list 

build.gradle, core/src/main/java/in/testpress/network/ErrorHandlingCallAdapterFactory.java, core/src/main/java/in/testpress/network/NetworkBoundResource.kt
- Updated retrofit to 2.9 version
=> Update retrofit to 2.9 version

core/build.gradle, core/schemas/in.testpress.database.TestpressDatabase/10.json, core/src/main/java/in/testpress/database/BaseDao.kt, core/src/main/java/in/testpress/database/Room.kt, core/src/main/java/in/testpress/database/dao/DiscussionPostDao.kt, core/src/main/java/in/testpress/database/dao/LastLoadedPageDataDao.kt, core/src/main/java/in/testpress/database/entities/CategoryEntity.kt, core/src/main/java/in/testpress/database/entities/DiscussionPostEntity.kt, core/src/main/java/in/testpress/database/entities/LastLoadedPageData.kt, core/src/main/java/in/testpress/database/entities/UserEntity.kt
- Added models for Discussion, User, Category and RemoteKeys 
- Added Dao for respective models
=> Add Room DB integration for discussions

core/src/main/java/in/testpress/models/NetworkCategory.kt, core/src/main/java/in/testpress/models/NetworkForum.kt, core/src/main/java/in/testpress/models/User.kt, core/src/main/java/in/testpress/network/TestpressAPIService.kt, core/src/test/java/in/testpress/network/NetworkTestMixin.kt, core/src/test/java/in/testpress/network/TestpressAPIServiceTest.kt, core/src/test/resources/discussions.json
- Added data classes for discussions
- Added API for discussions
No of test cases - 3
=> Added Network classes and API for discussions list

core/build.gradle, core/src/androidTest/java/in/testpress/core/database/DbTestMixin.kt, core/src/androidTest/java/in/testpress/network/DiscussionsMediatorTest.kt, core/src/main/java/in/testpress/database/dao/LastLoadedPageDataDao.kt, core/src/main/java/in/testpress/models/DiscussionRepository.kt, core/src/main/java/in/testpress/models/DiscussionsMediator.kt, core/src/main/java/in/testpress/network/FakeAPIClient.kt, core/src/main/java/in/testpress/network/TestpressAPIService.kt
- Added repository to fetch and store discussions in db
- We are using RoomDB as PagingSource
=> Added repository to fetch and store discussions in db

core/src/main/java/in/testpress/database/Room.kt, core/src/main/java/in/testpress/database/dao/CategoryDao.kt, core/src/main/java/in/testpress/database/dao/DiscussionPostDao.kt, core/src/main/java/in/testpress/database/entities/CategoryEntity.kt, core/src/main/java/in/testpress/models/DiscussionRepository.kt, core/src/main/java/in/testpress/models/DiscussionsMediator.kt, core/src/main/java/in/testpress/models/DomainCategory.kt, core/src/main/java/in/testpress/models/NetworkCategory.kt, core/src/main/java/in/testpress/network/TestpressAPIService.kt, core/src/main/java/in/testpress/ui/DiscussionViewModel.kt, core/src/main/java/in/testpress/ui/DiscussionsFilterFragment.kt, core/src/main/java/in/testpress/ui/fragments/DiscussionFragment.kt, core/src/main/java/in/testpress/ui/view/SlidingPaneLayout.kt, core/src/main/res/drawable-hdpi/testpress_rounded_green_button.xml, core/src/main/res/layout/discussion_list.xml, core/src/main/res/layout/discussions_filter.xml, core/src/main/res/layout/network_state_item.xml, core/src/main/res/menu/testpress_time_analytics_filter.xml
- Added sidebar which has categories filter and sorting support
=> Add categories filter and sorting support in Discussions list

core/src/main/java/in/testpress/models/DiscussionsMediator.kt, core/src/main/java/in/testpress/ui/DiscussionViewModel.kt, core/src/main/java/in/testpress/ui/fragments/DiscussionFragment.kt, core/src/main/res/drawable/ic_baseline_done_24.xml, core/src/main/res/drawable/ic_baseline_search_24.xml, core/src/main/res/menu/discussions_menu.xml
- Displayed search bar in discussions list action bar
- Added search support
=> Add search support in discussions list

core/src/main/java/in/testpress/models/InstituteSettings.java, course/src/main/java/in/testpress/course/fragments/VideoContentFragment.kt
- Added a field in institute modal and used that field to determine whether or not to show download option
=> Add support to enable or disable download option for video

course/src/main/java/in/testpress/course/util/VideoPlayerInterceptor.kt, store/build.gradle, store/src/main/java/in/testpress/store/payu/PayuPaymentGateway.kt
- Updated payu sdk to latest version
=> chore: Update payu sdk

course/src/main/res/layout-v29/layout_document_viewer.xml, course/src/main/res/layout-v29/layout_pdf_viewer.xml
- Issue is pdf viewer does not support dark mode.
- This is fixed by disabling dark mode for pdf viewer. This setting is only available for Android 10 and above
=> fix: Fix pdf is not displayed properly in dark mode

exam/src/main/java/in/testpress/exam/ui/ReviewQuestionsActivity.java
- Enabled the filter option in the solutions view to filter questions by correct, incorrect, and unanswered.
=> fix: Enable option to filter questions in solutions

core/src/main/java/in/testpress/Constants.kt, core/src/main/java/in/testpress/util/FullScreenChromeClient.java, course/src/main/java/in/testpress/course/fragments/VideoContentFragment.kt, course/src/main/java/in/testpress/course/fragments/WebViewVideoFragment.kt
- Issue is that the file upload button in the embed content was not working, it's because we haven't written the code to execute on the click choose file button, by default it was disabled.
- This is fixed by showing file picker on the button click.
=> fix: Fix embed content file upload not working

core/schemas/in.testpress.database.TestpressDatabase/13.json, core/schemas/in.testpress.database.TestpressDatabase/14.json, core/src/main/java/in/testpress/database/ContentEntity.kt, core/src/main/java/in/testpress/database/Room.kt, core/src/main/java/in/testpress/database/roommigration/RoomMigration13To14.kt, core/src/main/java/in/testpress/models/SSOUrl.kt, core/src/main/java/in/testpress/models/greendao/Content.java, core/src/main/java/in/testpress/models/greendao/ContentDao.java, core/src/main/java/in/testpress/network/AuthenticationService.java, core/src/main/java/in/testpress/network/TestpressApiClient.java, course/src/main/AndroidManifest.xml, course/src/main/java/in/testpress/course/domain/DomainContent.kt, course/src/main/java/in/testpress/course/domain/DomainExamContent.kt, course/src/main/java/in/testpress/course/fragments/BaseExamWidgetFragment.kt, course/src/main/java/in/testpress/course/network/NetworkContent.kt, course/src/main/java/in/testpress/course/ui/WebViewWithSSO.kt, testpressdaogenerator/src/main/java/in/testpress/TestpressSDKDaoGenerator.java
- In this commit we have added a new activity which will fetch sso url and open any url which is provided.
- We will provide exam start url to the new activity if exam is of type IELTS thus opening it in webview.
=> Add support to open IELTS exam in webview

core/src/main/java/in/testpress/models/InstituteSettings.java, course/src/main/java/in/testpress/course/fragments/QuizReviewFragment.kt, samples/src/main/java/in/testpress/samples/course/NavigationDrawerActivity.java
-  Added app name field in institute settings
-  Added watermark in QuizReviewFragment.kt using institute settings
-  Change the static watermark to dynamic watermark
Fixes # .
=> Add app_name field in institute settings

course/src/main/java/in/testpress/course/ui/BookmarksFragment.java, course/src/main/java/in/testpress/course/ui/ContentActivity.java, course/src/main/res/values/strings.xml
-  Added View button for pdf content in bookmarkActivity
- Pdf can't download from bookmark
Fixes # .
=> fix: Make bookmarked PDF non downloadable

course/src/main/java/in/testpress/course/fragments/ExamStartScreenFragment.kt, exam/src/main/res/layout/testpress_exam_details_layout.xml, exam/src/main/res/values/strings.xml
- Added validation for exam end date with current system date
- Added exam ended message in string.xml
-  Exam ended message not showing
=> fix: Fix display exam status

build.gradle, course/build.gradle, store/build.gradle
- Issue is payu dependency seems to be removed from jcenter and it has to be loaded from mavenCentral
- So we are using jcenter only for 2 dependencies and for others we are using mavenCentral
=> fix: Fix build error in project

exam/src/main/res/layout-xlarge/testpress_exam_details_layout.xml
-  Added exam end status message for large screen devices
Fixes # .
=> fix:not able to open exam detail view

course/src/main/res/layout/available_course_list_item.xml, store/src/main/java/in/testpress/store/ui/ProductsListAdapter.java, store/src/main/res/layout/testpress_products_list_item.xml, store/src/main/res/values/styles.xml
-  change the image aspect ratio to 16:9 in product listView and available course listView
- The image aspect ratio is changed to 16:9 on the web
Fixes #.
=> fix: Image aspect ratio to 16:9 in product list UI

course/src/main/res/layout/available_course_list_item.xml, store/src/main/java/in/testpress/store/ui/ProductsListAdapter.java
-  Set  thumbnail image without radius in available courses list view
Fixes #.
=> fix: Set thumbnail image without radius in available courses list view

course/src/main/java/in/testpress/course/fragments/VideoConferenceFragment.kt, course/src/main/java/in/testpress/course/util/ZoomMeetHandler.kt
- Created chapter content attempt for a video conference after the user joined the meeting.
=> fix: Create content attempt for video conference 

exam/src/main/java/in/testpress/exam/ui/ReviewStatsFragment.java, exam/src/main/res/layout/testpress_fragment_review_stats.xml
- Change field name advanceAnalytics to advancedAnalytics in testpress_fragment_review_stats.xml and ReviewStartFragment.Java
Fixes # .
=> refactor: Change variable name to advancedAnalytics

core/src/main/java/in/testpress/models/InstituteSettings.java, course/src/main/java/in/testpress/course/fragments/VideoContentFragment.kt, course/src/main/res/layout/layout_input_username.xml, samples/src/main/java/in/testpress/samples/course/NavigationDrawerActivity.java
- Added maxAllowedDownloadedVideos field in institute settings
- validate download count according to downloaded video and max download limit.
-  Set download limit for offline video
Fixes #.
=> fix: Add offline video download limit

exam/src/main/res/layout/testpress_fragment_review_stats.xml
-  Refactor advanced analytics variable name in testpress_review_fragment_start.xml
- #461 in this commit
-  Missed changing the variable name to advanced analytics
Fixes #.
=> fix: Review layout not visible

core/schemas/in.testpress.database.TestpressDatabase/15.json, core/src/main/java/in/testpress/database/Room.kt, core/src/main/java/in/testpress/database/dao/ProductCategoryDao.kt, core/src/main/java/in/testpress/database/entities/ProductCategoryEntity.kt, core/src/main/java/in/testpress/database/roommigration/RoomMigration14To15.kt
- Added ProductCategoryEntity model in the room DB
- Added room DB migration 14 to 15
- Need to show product list according to categories as shown on the web
Fixes #.
=> fix: Add ProductCategoryEntity model in room database

course/src/main/java/in/testpress/course/TestpressCourse.java, course/src/main/java/in/testpress/course/fragments/BaseContentListFragment.kt, course/src/main/java/in/testpress/course/ui/ContentListFragment.kt, course/src/main/res/layout/base_content_list_layout.xml
- Added BaseContentListFragment
- Added base_content_list_layout.xml
- ContentListFragment is derived from BaseContentListFragment
=> refactor: Content list fragment

exam/src/main/java/in/testpress/exam/ui/ReviewQuestionsFragment.java
- Question review page not loading properly 
- In this commit dd191da we pause the webView if not visible to user
- Now we handled both conditions if webView is Invisible we pause the webView else we resume the webView
=> fix: Question review page not loading

core/schemas/in.testpress.database.TestpressDatabase/17.json, core/src/main/java/in/testpress/database/Room.kt, core/src/main/java/in/testpress/database/entities/RunningContentEntity.kt, core/src/main/java/in/testpress/database/entities/RunningContentRemoteKeys.kt, core/src/main/java/in/testpress/database/entities/UpcomingContentEntity.kt, core/src/main/java/in/testpress/database/entities/UpcomingContentRemoteKeys.kt, core/src/main/java/in/testpress/database/roommigration/RoomMigration16To17.kt
- Added database model class and pagination class
- upgrade Room DB version to 17
- Added Room migration 16_17
=> feat: Add running upcoming database model class

core/src/main/assets/testpress_questions_typebase.css
- In this commit, we decreased the font weight and modified the color of the Report button
=> fix: Report button UI in review question view

core/src/main/java/in/testpress/database/dao/ContentLiteDao.kt, core/src/main/java/in/testpress/database/dao/ContentLiteRemoteKeyDao.kt, course/src/main/java/in/testpress/course/adapter/CourseContentListAdapter .kt, course/src/main/java/in/testpress/course/adapter/viewholder/RunningContentItemViewHolder.kt, course/src/main/java/in/testpress/course/adapter/viewholder/UpcomingContentItemViewHolder.kt, course/src/main/java/in/testpress/course/api/TestpressCourseApiClient.java, course/src/main/java/in/testpress/course/fragments/CourseContentListFragment .kt, course/src/main/java/in/testpress/course/network/CourseService.kt, course/src/main/java/in/testpress/course/pagination/CourseContentsRemoteMediator.kt, course/src/main/java/in/testpress/course/repository/CourseContentsRepository.kt, course/src/main/res/values/strings.xml, samples/src/main/java/in/testpress/samples/course/NavigationDrawerActivity.java, samples/src/main/res/menu/course_drawer_items.xml
- The commit includes the addition of the Upcoming content functionality that was recently added to the web.
- A button is added in the sample app, which takes Course ID as input and shows the upcoming contents list
=> feat : Upcoming content list UI

course/src/main/java/in/testpress/course/ui/ChapterDetailActivity.java, course/src/main/java/in/testpress/course/ui/CourseDetailsTabAdapter.java, exam/src/main/res/layout/testpress_fragment_carousel.xml
-  The user interface for the course list now includes a "Running" tab and an "Upcoming" tab.
-  Running content and upcoming content are shown in respective tabs.
=> feat: Integrate running content and upcoming content in course list view

exam/src/main/java/in/testpress/exam/ui/ReviewStatsFragment.java, exam/src/main/res/layout/testpress_fragment_review_stats.xml, exam/src/main/res/values/strings.xml
- Added layout to show rank publish date in relative time format in ReviewStartFragment
=> feat: Show Rank publish date in review start page

core/build.gradle, core/src/androidTest/java/in/testpress/core/database/ContentDaoTest.kt, core/src/androidTest/java/in/testpress/core/database/ProductsListDaoTest.kt, core/src/androidTest/java/in/testpress/network/DiscussionsMediatorTest.kt, core/src/test/java/in/testpress/core/TestpressApiClientTest.java, core/src/test/java/in/testpress/ui/UserDevicesActivityTest.java
- Increased roboelectric package version to 4.9.2
- Changed contentEntity model in ContentDaoTest 
- Fixed failing test case
=> fix: Core library test cases failing

core/src/test/java/in/testpress/ui/EmptyViewFragmentTest.kt
=> test: Fix failing test cases in EmptyViewFragment

core/build.gradle
- Update paging library 3.0.0 to 3.1.1
=> fix: Update paging dependencies in core library

build.gradle, core/build.gradle, course/build.gradle
- In this commit, we extract the paging dependencies to the top-level Gradle file. By doing so, we improve the organization and maintainability of our project's build configuration.
=> refactor: Extract paging dependencies to top level gradle

build.gradle
- AndroidX constraintlayout 1.1.3 -> 2.0.4
=> fix: Update constraint layout dependencies in course library

exam/src/main/java/in/testpress/exam/ui/ReviewStatsFragment.java
- Extract displayTestReport() in ReviewStatsFragment
=> refactor: Extract to meaningful method

exam/src/main/java/in/testpress/exam/ui/ReviewStatsFragment.java
- This commit refactors the showOrHidePercentageLayout() and showOrHideScoreLayout() methods in the code. The changes improve readability and simplify the conditions for showing or hiding the corresponding layouts.
=> refactor: Methods in Review ReviewStatsFragment

core/src/main/java/in/testpress/ui/AbstractWebViewActivity.kt, core/src/main/java/in/testpress/ui/WebViewWithSSOActivity.kt, samples/src/main/java/in/testpress/samples/course/CourseSampleActivity.java
- This commit involves extracting the Abstract class from WebViewWithSSOActivity and transforming WebViewWithSSOActivity into a subclass.
- By doing this, we can extend this abstract class and successfully transmit the JavaScript interface to the webview. Additionally, we can create an independent webview activity.
=> refactor: Extract Abstract class from WebViewWithSSOActivity

core/src/main/java/in/testpress/fragments/WebViewFragment.kt, course/src/main/AndroidManifest.xml, course/src/main/java/in/testpress/course/ui/CustomTestGenerationActivity.kt, samples/src/main/java/in/testpress/samples/course/CourseSampleActivity.java, samples/src/main/res/layout/activity_open_in.xml
- In this commit, we added a custom test generation feature and also added a button in the sample app to access this feature by providing a course slug as input
=> feat: Add Custom test generation 

course/src/main/java/in/testpress/course/AvailableCourseListAdapter.java, course/src/main/res/layout/available_course_list_item.xml
- Product list item view UI was degraded in this commit 800ddd2
=> fix: UI Misalignment in Product list view

core/src/main/java/in/testpress/models/InstituteSettings.java, store/build.gradle, store/src/main/java/in/testpress/store/PaymentGatewayFactory.kt, store/src/main/java/in/testpress/store/network/StoreApiClient.java, store/src/main/java/in/testpress/store/razorpay/RazorpayPaymentGateway.kt
- We recently integrated Razorpay payment gateway in testpress web portal.
- This commit integrates razorpay in android app to show checkout form in-app.
- 
- 
Fixes # .
=> feat: Integrate Razorpay payment gateway

course/src/main/java/in/testpress/course/ui/ChaptersListFragment.java
- In the web custom test URL was modified recently.
- In this commit update the custom test URL in ChaptersListFragment.
=> fix: Update custom test URL in chapters list view

course/src/main/java/in/testpress/course/ui/ChaptersListFragment.java, samples/src/main/java/in/testpress/samples/course/CourseSampleActivity.java
- In this commit, we are adding a query param in the custom test generation URL to identify the request that is coming from testpress android app or not.
=> fix: Update custom test generation URL

build.gradle, core/src/main/java/in/testpress/ui/fragments/DiscussionFragment.kt, core/src/main/java/in/testpress/util/WebViewUtils.java, course/src/main/java/in/testpress/course/fragments/DownloadsFragment.kt, course/src/main/java/in/testpress/course/fragments/VideoContentFragment.kt
- Update the Android Target SDK version to 33 and make the necessary code changes for this update.
=> fix: Update Android Target SDK version and Compile SDK version to 33

course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java
- Users can able to record the screen in Portrait mode
- By adding a secure screen flag to the activity while initializing the exoplayer util
=> fix: Screen Recording in portrait Mode

course/src/main/AndroidManifest.xml, course/src/main/java/in/testpress/course/util/AnimationUtil.kt, course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java, course/src/main/java/in/testpress/course/util/PinchToZoomGesture.kt, course/src/main/java/in/testpress/course/util/VideoTouchDragHandler.kt, course/src/main/java/in/testpress/course/util/extension/TextView.kt, course/src/main/res/drawable/exoplayer_zoom_mode_round_background.xml, course/src/main/res/drawable/exoplayer_zoom_mode_square_background.xml, course/src/main/res/layout/content_detail_activity.xml, course/src/main/res/layout/testpress_exo_player_view.xml, samples/src/main/java/in/testpress/samples/core/TestpressCoreSampleActivity.java
- Added Pinch to zoom support in Player view
- This functionality works only in Fullscreen mode
=> feat: Add pinch to zoom support in Video player

course/src/main/java/in/testpress/course/fragments/LoadingQuestionsFragment.kt, course/src/main/java/in/testpress/course/repository/QuizExamRepository.kt, course/src/main/java/in/testpress/course/ui/QuizActivity.kt, course/src/main/java/in/testpress/course/viewmodels/QuizExamViewModel.kt, course/src/main/java/in/testpress/course/viewmodels/QuizViewModel.kt
- changed attempt name to contentAttempt
=> refactor: Refactor meaningful variable name in Quiz Exam Template

course/src/main/java/in/testpress/course/domain/DomainContent.kt, course/src/main/java/in/testpress/course/domain/DomainLiveStream.kt, course/src/main/java/in/testpress/course/fragments/ContentLoadingFragment.kt, course/src/main/java/in/testpress/course/fragments/LiveStreamFragment.kt, course/src/main/res/layout/fragment_live_stream.xml
- Created a live stream content view using the existing exoPlayer and its util class for video playback.
=> feat: Create a live stream content viewing page

course/src/main/java/in/testpress/course/domain/DomainLiveStream.kt, course/src/main/java/in/testpress/course/fragments/LiveStreamFragment.kt, course/src/main/res/layout/fragment_live_stream.xml
- Stored the 'chat_embed_url' from the network response in the database, and embedded a WebView with that URL below the live stream player.
=> feat: Embed chat in live stream view page

build.gradle, course/src/main/java/in/testpress/course/util/SimpleInMeetingListener.kt
- In this commit, we update Zoom SDK version to 5.13.5.11583
- Increased android minSdkVersion to 23
=> fix: Update zoom SDK version 5.13.5.11583

core/src/main/java/in/testpress/ui/BaseToolBarActivity.kt, course/src/main/java/in/testpress/course/ui/QuizActivity.kt
- In this commit, we are hiding the toolbar logo in the quiz activity. While the user taking the quiz exam institute logo is appear in ToolBar
=> fix: Hide toolbar logo in quiz activity

core/src/main/AndroidManifest.xml, core/src/main/java/in/testpress/util/CommonUtils.java, course/src/main/java/in/testpress/course/ui/CourseListActivity.java, course/src/main/java/in/testpress/course/ui/CourseListFragment.java
- In this commit, we add a custom store WebView for the Epradipa App.
- We are handling using the package name for other institutes we are retaining the previous behavior.
- Also we are passing the user name and password in url query param for authentication.
=> fix: Add custom store webview for Epradipa

course/src/main/java/in/testpress/course/fragments/WebViewVideoFragment.kt
- When embedding video content, users have the ability to navigate to other apps, such as YouTube and Chrome, by clicking the video title or the YouTube branding logo. However, in this commit, we prevent users from accessing other apps by determining if the embedded video content originates from YouTube. Additionally, we disable the long-press option in the webView to prevent users from selecting text or video URLs.
=> fix: Prevent users from navigating to other apps from video content activity

course/src/main/java/in/testpress/course/fragments/WebViewVideoFragment.kt, course/src/main/res/layout/video_webview.xml
- In the previous version, our web view loading was delayed, resulting in a laggy user experience. In this commit, we have introduced a progress bar to improve the user experience by displaying loading progress until the web view fully loads.
=> fix: Implement Loading Progress Bar for WebView Loading

core/src/main/java/in/testpress/util/FullScreenChromeClient.java, core/src/main/res/layout/testpress_toolbar.xml, course/src/main/java/in/testpress/course/fragments/WebViewVideoFragment.kt
- WebView Video Fragment does not support landscape orientation, but in this commit, we have implemented support for landscape orientation.
=> fix: Implementing Landscape View in WebView Video Fragment

core/src/main/res/layout/course_preview_layout.xml
- Removed unwanted bottom margin in chapter list view layout
=> fix: Improve UI for chapter list view

core/src/main/java/in/testpress/models/InstituteSettings.java, course/src/main/java/in/testpress/course/ui/CourseListFragment.java, samples/src/main/java/in/testpress/samples/course/CourseSampleActivity.java
- In this commit, we added `disableStoreInApp` field in InstituteSettings Model.
- Hereafter we show and hide the store based on these two fields `disableStoreInApp` and `storeEnabled`.
=> enhancement: Add `disableStoreInApp` field in InstituteSettings Model

core/src/main/java/in/testpress/fragments/WebViewFragment.kt
- In this commit, we adding the custom user agent in android webView to identify the Testpress Android App
=> enhancement: Add custom user agent in webview

build.gradle, core/build.gradle, core/src/main/java/in/testpress/ui/fragments/DiscussionFragment.kt
- In this commit, we updated the Kotlin version `1.5.0` to `1.6.0`, and we also updated the corresponding room database version `2.3.0` to `2.4.0`.
- Added room pagination dependency it was separated from the room runtime package in the room version `2.4.0-alpha04`
=> enhancement: Update kotlin version to 1.6.0

core/src/main/java/in/testpress/util/DateUtils.kt, course/src/main/java/in/testpress/course/adapter/CourseContentListAdapter .kt, course/src/main/java/in/testpress/course/adapter/viewholder/RunningContentItemViewHolder.kt, course/src/main/java/in/testpress/course/adapter/viewholder/UpcomingContentItemViewHolder.kt, course/src/main/res/layout/running_upcoming_list_item.xml
- Added standard date format instead of humanized format in the running content list view in this commit.
=> refactor: Display standard date format instead of humanized format.

build.gradle
- Updated Kotlin version from `1.7.0` to `1.8.0`.
=>  enhancement: Update Kotlin version to 1.8.0

course/src/main/java/in/testpress/course/fragments/ContentLoadingFragment.kt, course/src/main/java/in/testpress/course/fragments/VideoContentFragment.kt
- In this commit, we are changing the access modifiers to `ContentFragmentFactory` and `VideoContentFragment`. This enables users to add custom video content fragments using our SDK
=> enhancement: Change access modifiers to `ContentFragmentFactory` and `VideoContentFragment`

core/src/main/java/in/testpress/fragments/WebViewFragment.kt, core/src/main/java/in/testpress/ui/AbstractWebViewActivity.kt, course/src/main/java/in/testpress/course/fragments/LiveStreamFragment.kt, course/src/main/java/in/testpress/course/ui/ChaptersListFragment.java, course/src/main/java/in/testpress/course/ui/CourseListFragment.java, course/src/main/java/in/testpress/course/ui/MyCoursesFragment.java, samples/src/main/java/in/testpress/samples/course/CourseSampleActivity.java
- In this commit, we added authentication in webview requests and removed the previous user SSO login process.
- This change allows users to be authenticated directly with a JWT token passed in the webview request, eliminating the need for an additional API call to generate an SSO token.
=> enhancement: Add JWT Authentication in webview

core/src/main/java/in/testpress/database/dao/ExamQuestionDao.kt, core/src/main/java/in/testpress/database/dao/OfflineExamDao.kt, course/src/main/java/in/testpress/course/repository/OfflineExamRepository.kt, course/src/main/java/in/testpress/course/viewmodels/OfflineExamViewModel.kt, samples/src/main/java/in/testpress/samples/course/OfflineExamSampleActivity.kt, samples/src/main/res/layout/activity_offline_exam_sample.xml, samples/src/main/res/layout/sample_item_offline_exam.xml
- Added an offline download list view in the sample app.
- Included the option to delete downloaded exams in the sample app.
=> feat: Add support to list downloaded exams and delete exams

core/schemas/in.testpress.database.TestpressDatabase/24.json, core/src/main/java/in/testpress/database/Room.kt, core/src/main/java/in/testpress/database/entities/OfflineAttempt.kt, core/src/main/java/in/testpress/database/entities/OfflineAttemptSection.kt, core/src/main/java/in/testpress/database/entities/OfflineCourseAttempt.kt, core/src/main/java/in/testpress/database/roommigration/RoomMigration23To24.kt
- Introduced new models to support offline attempts
- Implemented room migration scripts from version 23 to 24.
=>  feat: Add models for Offline Attempts

exam/src/main/java/in/testpress/exam/repository/AttemptRepository.kt, exam/src/main/java/in/testpress/exam/ui/TestFragment.java, exam/src/main/java/in/testpress/exam/ui/viewmodel/AttemptViewModel.kt
- Implemented the Repository pattern for save results in `TestFragment`.
- Previously, this functionality was handled directly within the `TestFragment`.
=> enhancement: Add method to update answer via repository

exam/src/main/java/in/testpress/exam/repository/AttemptRepository.kt, exam/src/main/java/in/testpress/exam/ui/TestFragment.java, exam/src/main/java/in/testpress/exam/ui/viewmodel/AttemptViewModel.kt
- In this commit, added methods to end content attempt and attempt for the exam.
- Implemented these methods following the repository pattern.
=> feat: Add method to end exam via repository

exam/src/main/java/in/testpress/exam/ui/TestActivity.java, exam/src/main/java/in/testpress/exam/ui/TestFragment.java
- In this commit, refactored the handling of Attempt, Question, and Section URLs based on whether the exam is offline or online.
=> refactor: Attempt, Question, Section URL Handling Based on Offline Exam Status

core/src/main/java/in/testpress/models/InstituteSettings.java, core/src/main/java/in/testpress/util/WebViewUtils.java
- Added `disableImageFullscreenZoomInExam` field in `InstituteSetting` to manage image click events in exams and prevent fullscreen zooming.
=> enhancement: Add option to disable image zooming in exams

exam/src/main/java/in/testpress/exam/repository/ExamRepository.kt
- Previously, when creating an offline attempt, the exam duration was used as the attempt duration.
- This behavior has been changed to match the online exam behavior. If the user attempts the exam and it is set to end in 2 minutes (even if the total duration is 10 minutes), we now only consider the 2 minutes instead of the full 10 minutes.
=> fix: Auto submission in offline mode not working with exam expiry time

course/src/main/java/in/testpress/course/util/SimpleInMeetingListener.kt, course/src/main/java/in/testpress/course/viewmodels/OfflineVideoViewModel.kt, mobilertc/build.gradle
- In this commit, we update the Zoom SDK version `5.15.12.10095` to `5.16.10.17706`.
- Updated corresponding code changes
=> enhancement: Update zoom SDK version `5.16.10.17706`

course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java
- In this commit, we've added a custom Sentry object to track player errors in detail.
=> enhancement: Add custom Sentry object to capture detailed error information

core/src/main/java/in/testpress/models/InstituteSettings.java, course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java, course/src/main/java/in/testpress/course/util/WatermarkOverlay.kt, course/src/main/res/layout/exo_player_view.xml, samples/src/main/java/in/testpress/samples/core/TestpressCoreSampleActivity.java
- Added `videoWatermarkType` and `videoWatermarkPosition` to `InstituteSettings`.
- Implemented dynamic and static watermark overlays in `ExoPlayerUtil`.
- Supports configurable positions and enhances content security.
=> enhancement: Add support for configurable video watermarking

course/src/main/java/in/testpress/course/ui/CustomTestGenerationActivity.kt, course/src/main/res/values/strings.xml
- Added handling for server errors in the exception block to provide a more specific error message.
=> fix: Add server error message for custom test generation

course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java
- This PR optimizes API calls in ExoPlayerUtil by introducing the following changes:
- Pause Handling: Ensures updateVideoAttempt is called only when the user explicitly pauses the video.
- Seek Handling: Implements a debounce mechanism for updateVideoAttempt during seek operations, avoiding redundant API calls while seeking.
=> fix: Prevent unwanted API calls during video seek and pause events

course/src/main/java/in/testpress/course/fragments/BaseContentListFragment.kt, course/src/main/java/in/testpress/course/fragments/CourseContentListFragment .kt, course/src/main/java/in/testpress/course/ui/ContentListFragment.kt, course/src/main/res/layout/base_content_list_layout.xml
- This PR adds a swipe-to-refresh feature for the content list view.
- Added SwipeRefreshLayout to the shared content list XML layout.
- Enabled swipe-to-refresh in ContentListFragment.
- Disabled swipe-to-refresh in CourseContentListFragment for running and upcoming content lists.
=> enhancement: Add swipe-to-refresh for content list view

course/src/main/java/in/testpress/course/util/ExoPlayerUtil.java
- Previously, we displayed a generic error message for ExoPlayer error code 4001 and 4003. This error typically occurs due to insufficient system resources, missing or incompatible decoder libraries, or similar issues. Restarting the device usually resolves it.
- We added a custom error message specifically for error code 4001 and 4003.
- Included a troubleshooting link within the message for further assistance.
=> fix: Display custom message for Error code 4001 and 4003

course/src/main/java/in/testpress/course/fragments/VideoConferenceFragment.kt
- The customer key was not being set the first time a user attended a Zoom class, as the profile details were not being fetched initially for new users. The app tried to start the Zoom class before receiving the profile response, leading to an empty customer key.
- Profile details were being accessed before being fetched, causing a delay in setting up the Zoom class with the correct customer key.
- Added a check to verify if the profile details are null. If they are, the app now fetches the profile details first before attempting to start the Zoom class, ensuring that the customer key is correctly set.
=> fix: Ensure profile details are fetched before starting Zoom class to set customer key

store/src/main/java/in/testpress/store/ui/ProductDetailsActivity.java, store/src/main/res/drawable/baseline_check_24.xml, store/src/main/res/drawable/button_apply_coupon.xml, store/src/main/res/drawable/disabled_button_background.xml, store/src/main/res/drawable/edittext_background.xml, store/src/main/res/drawable/edittext_default.xml, store/src/main/res/drawable/edittext_focused.xml, store/src/main/res/drawable/enabled_button_background.xml, store/src/main/res/drawable/green_button_background.xml, store/src/main/res/drawable/rounded_top_background.xml, store/src/main/res/layout/testpress_product_details_layout.xml
- Added UI elements for applying a coupon code, including an input field and an apply button.
- Implemented logic to handle coupon code input and button enable/disable state.
- Displayed a message when a coupon is applied and hid the keyboard after applying.
- Updated testpress_product_details_layout.xml to include a section for coupon input and updated button layout.
- Added new drawable resources for button and edit text styling.
- Ensured visibility toggling for the discount input section when clicking "Have a discount code?"
=> feat: Add coupon code UI

store/src/main/java/in/testpress/store/network/ProductService.java, store/src/main/java/in/testpress/store/network/StoreApiClient.java, store/src/main/java/in/testpress/store/ui/OrderConfirmActivity.java, store/src/main/java/in/testpress/store/ui/ProductDetailsActivity.java, store/src/main/java/in/testpress/store/util/Util.kt, store/src/main/res/drawable/green_button_background.xml, store/src/main/res/drawable/rounded_top_background.xml
- This PR introduces support for applying coupons during the order process. Key changes include:
- Added a new API method to apply coupons to an order (applyCoupon).
- Integrated coupon application logic in ProductDetailsActivity:
- Creates an order before applying the coupon if not already created.
- Displays the discount and updates the price UI after successful coupon application.
- Handles network errors and displays appropriate messages.
- Ensured that OrderConfirmActivity skips redundant order creation if a coupon is already applied.
- This improves the user experience by allowing them to apply discounts before order confirmation.
=> feat: Add coupon code Implementation

store/src/main/java/in/testpress/store/ui/ProductListFragmentV2.kt
- Renamed productListViewModel to productsViewModel and productListAdapter to productsAdapter to reflect naming consistency.
- Consolidated RecyclerView setup and pagination logic into a cleaner setupProductList method with getPaginationScrollListener.
- Split observeViewModel into observeProducts under observeViewModels for better modularity and potential future extensions.
- Renamed method names for product load state handling:
- Enhances readability, maintainability, and follows clearer naming conventions without changing business logic.
=> refactor: Rename variables and restructure methods in product fragment

core/schemas/in.testpress.database.TestpressDatabase/38.json, core/src/main/java/in/testpress/database/Room.kt, core/src/main/java/in/testpress/database/roommigration/RoomMigration37To38.kt
- Migrated Room database from version 37 to 38
- Added isAIEnabled column in ContentEntity
=> fix: Migrate to version 38 with isAIEnabled column
